#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmecaApp
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class CaseHearingList : WebViewTemplate
{

#line hidden

#line 1 "CaseHearingList.cshtml"
public System.Collections.Generic.List<UmecaApp.HearingFormatTblDto> Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 3 "CaseHearingList.cshtml"
  
	Layout = "UmecaApp.HeadSupervition";


#line default
#line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    function hearing(idCase){\r\n\t\twindow.location.replace(\'hybrid:Supervision/H" +
"earingFormatList?idCase=\'+idCase);\r\n    }\r\n    </script>\r\n<h2");

WriteLiteral(" class=\"element-center\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-comments-alt \"");

WriteLiteral("></i>&nbsp;&nbsp;Formato de Audiencia</h2>\r\n<br /> \r\n<div");

WriteLiteral(" id=\"toolbar2\"");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n    <a");

WriteAttribute ("href", " href=\"", "\""

#line 14 "CaseHearingList.cshtml"
, Tuple.Create<string,object,bool> ("", Url.Action("CaseConditionalReprieveEditNew","Supervision")

#line default
#line hidden
, false)
);
WriteLiteral(">\r\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" id=\"btnAdd\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></i>\r\n    </button></a>\r\n</div>\r\n    <table");

WriteLiteral(" data-toggle=\"table\"");

WriteLiteral(" data-page-size=\"10\"");

WriteLiteral(" data-page-list=\"[10, 20, 30]\"");

WriteLiteral("\r\n     data-pagination=\"true\"");

WriteLiteral(" data-height=\"250\"");

WriteLiteral("\r\n     data-striped=\"true\"");

WriteLiteral(" data-search=\"true\"");

WriteLiteral(" \r\n     data-search-align=\"right\"");

WriteLiteral(" data-toolbar=\"#toolbar2\"");

WriteLiteral(">\r\n    <thead>\r\n    <tr>\r\n        <th>Carpeta de Investigaci&oacute;n</th>\r\n     " +
"   <th>Carpeta Judicial</th>\r\n        <th>Nombre Completo</th>\r\n        <th>Esta" +
"tus</th>\r\n        <th>Acci&oacute;n</th>\r\n    </tr>\r\n    </thead>\r\n    <tbody>\r\n" +
"");


#line 33 "CaseHearingList.cshtml"
    

#line default
#line hidden

#line 33 "CaseHearingList.cshtml"
     foreach(var CaseHearing in Model) {


#line default
#line hidden
WriteLiteral("    <tr");

WriteLiteral(" id=\"tr-id-1\"");

WriteLiteral(" class=\"tr-class-1\"");

WriteLiteral(">\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 36 "CaseHearingList.cshtml"
       Write(CaseHearing.IdFolder);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 39 "CaseHearingList.cshtml"
       Write(CaseHearing.IdMP);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 42 "CaseHearingList.cshtml"
        Write(CaseHearing.Name+" "+CaseHearing.LastNameP+" "+CaseHearing.LastNameM);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("       \t\t");


#line 45 "CaseHearingList.cshtml"
       Write(CaseHearing.StatusCode);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");


#line 48 "CaseHearingList.cshtml"
         

#line default
#line hidden

#line 48 "CaseHearingList.cshtml"
          if(CaseHearing.StatusCode=="ST_CASE_CONDITIONAL_REPRIEVE") {


#line default
#line hidden
WriteLiteral("         \t<a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" style=\"display:inline-block;\"");

WriteLiteral(" title=\"Gestionar formatos de audiencia\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "hearing(", true)

#line 49 "CaseHearingList.cshtml"
                                                                                   , Tuple.Create<string,object,bool> ("", CaseHearing.CaseId

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ");", true)
);
WriteLiteral("><i");

WriteLiteral(" class=\"icon-plus\"");

WriteLiteral("></i></a>\r\n");


#line 50 "CaseHearingList.cshtml"
         }
         else if(CaseHearing.StatusCode=="INCOMPLETE") {


#line default
#line hidden
WriteLiteral("         \t<a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" style=\"display:inline-block;\"");

WriteLiteral(" title=\"Visualizar formatos de audiencia\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "hearing(", true)

#line 52 "CaseHearingList.cshtml"
                                                                                    , Tuple.Create<string,object,bool> ("", CaseHearing.CaseId

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ");", true)
);
WriteLiteral("><span");

WriteLiteral(" class=\"icon-pencil\"");

WriteLiteral("></span></a>\r\n");


#line 53 "CaseHearingList.cshtml"
         }else{


#line default
#line hidden
WriteLiteral("         \t<a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" style=\"display:inline-block;\"");

WriteLiteral(" title=\"Visualizar formatos de audiencia\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "hearing(", true)

#line 54 "CaseHearingList.cshtml"
                                                                                    , Tuple.Create<string,object,bool> ("", CaseHearing.CaseId

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ");", true)
);
WriteLiteral("><span");

WriteLiteral(" class=\"icon-eye-open\"");

WriteLiteral("></span></a>\r\n");


#line 55 "CaseHearingList.cshtml"
         }


#line default
#line hidden
WriteLiteral("        </td>\r\n    </tr>\r\n");


#line 58 "CaseHearingList.cshtml"
}


#line default
#line hidden
WriteLiteral("    </tbody>\r\n</table>");

}
}
}
#pragma warning restore 1591
