#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmecaApp
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class HearingFormatList : WebViewTemplate
{

#line hidden

#line 1 "HearingFormatList.cshtml"
public System.Collections.Generic.List<UmecaApp.HearingFormatGrid> Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 3 "HearingFormatList.cshtml"
  
	Layout = "UmecaApp.HeadSupervition";


#line default
#line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    function cancelari(){\r\n\t\twindow.location.replace(\'hybrid:Login/Index\');\r\n " +
"   } \r\n    function editFormatoAudiencia(fuente){\r\n\t\twindow.location.replace(\'hy" +
"brid:Login/Index\');\r\n    }\r\n\r\n    </script>\r\n<h2");

WriteLiteral(" class=\"element-center\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-comments-alt \"");

WriteLiteral("></i>&nbsp;&nbsp;Formato de Audiencia</h2>\r\n<br />\r\n<div");

WriteLiteral(" id=\"toolbar2\"");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n    <a");

WriteAttribute ("href", " href=\"", "\""

#line 18 "HearingFormatList.cshtml"
, Tuple.Create<string,object,bool> ("", Url.Action("HearingFormatEditNew","Meeting")

#line default
#line hidden
, false)
);
WriteLiteral(">\r\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" id=\"btnAdd\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></i>\r\n    </button></a>\r\n</div>\r\n    <table");

WriteLiteral(" data-toggle=\"table\"");

WriteLiteral(" data-page-size=\"10\"");

WriteLiteral(" data-page-list=\"[10, 20, 30]\"");

WriteLiteral("\r\n     data-pagination=\"true\"");

WriteLiteral(" data-height=\"250\"");

WriteLiteral("\r\n     data-striped=\"true\"");

WriteLiteral(" data-search=\"true\"");

WriteLiteral(" \r\n     data-search-align=\"right\"");

WriteLiteral(" data-toolbar=\"#toolbar2\"");

WriteLiteral(@">
    <thead>
    <tr>
        <th>Carpeta de Investigaci&oacute;n</th>
        <th>Carpeta Judicial</th>
        <th>Nombre Completo</th>
        <th>Fecha de Registro</th>
        <th>Supervisor</th>
        <th>Audiencia</th>
        <th>Ampliaci&oacute;n de plazo</th>
        <th>Vinculaci&oacute;n a proceso</th>
        <th>Finalizado</th>
        <th>Acci&oacute;n</th>
    </tr>
    </thead>
    <tbody>
");


#line 42 "HearingFormatList.cshtml"
    

#line default
#line hidden

#line 42 "HearingFormatList.cshtml"
     foreach(var formatoAudiencia in Model) {


#line default
#line hidden
WriteLiteral("    <tr");

WriteLiteral(" id=\"tr-id-1\"");

WriteLiteral(" class=\"tr-class-1\"");

WriteLiteral(">\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 45 "HearingFormatList.cshtml"
       Write(formatoAudiencia.IdFolder);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 48 "HearingFormatList.cshtml"
       Write(formatoAudiencia.IdMP);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 51 "HearingFormatList.cshtml"
       Write(formatoAudiencia.Fullname);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 54 "HearingFormatList.cshtml"
       Write(formatoAudiencia.RegisterTime);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 57 "HearingFormatList.cshtml"
       Write(formatoAudiencia.UserName);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 60 "HearingFormatList.cshtml"
       Write(formatoAudiencia.HearingType);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 63 "HearingFormatList.cshtml"
       Write(formatoAudiencia.Extension);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 66 "HearingFormatList.cshtml"
       Write(formatoAudiencia.ProcessVinc);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("       \t\t");


#line 69 "HearingFormatList.cshtml"
       Write(formatoAudiencia.FinishedStr);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n         \t<a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" style=\"display:inline-block;\"");

WriteLiteral(" title=\"Visualizar formatos de audiencia\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "visualizeFormat(", true)

#line 72 "HearingFormatList.cshtml"
                                                                                            , Tuple.Create<string,object,bool> ("", formatoAudiencia.CaseId

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ");", true)
);
WriteLiteral("><span");

WriteLiteral(" class=\"icon-eye-open\"");

WriteLiteral("></span></a>\r\n        </td>\r\n    </tr>\r\n");


#line 75 "HearingFormatList.cshtml"
}


#line default
#line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n\t<!--<span class=\"btn btn-default btn-sm\" onclick=\"cancel" +
"ari();\">\r\n        Cancelar\r\n    </span>-->");

}
}
}
#pragma warning restore 1591
