#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmecaApp
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class HearingFormatList : WebViewTemplate
{

#line hidden

#line 1 "HearingFormatList.cshtml"
public UmecaApp.HearingFormatTblDto Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 4 "HearingFormatList.cshtml"
  
	Layout = "UmecaApp.HeadSupervition";


#line default
#line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    function cancelari(){
		window.location.replace('hybrid:Login/Index');
    } 
    function visualizeFormat(fuente,formato){
		window.location.replace('hybrid:Supervision/HearingFormatVisualize?idCase='+fuente+'&idFormato='+formato);
    }
    function editFormatoAudiencia(fuente,formato){
		window.location.replace('hybrid:Supervision/HearingFormatUpsert?idCase='+fuente+'&idFormato='+formato);
    }
    function newFormatoAudiencia(fuente){
		window.location.replace('hybrid:Supervision/HearingFormatUpsert?idCase='+fuente+'&idFormato=0');
    }
    </script>
<h2");

WriteLiteral(" class=\"element-center\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-comments-alt \"");

WriteLiteral("></i>&nbsp;&nbsp;Formato de Audiencia</h2>\r\n");


#line 22 "HearingFormatList.cshtml"
 if(Model.message!=null){


#line default
#line hidden
WriteLiteral("\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" onclick=\"javascript:$(this).hide();\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" msg=\"MsgError\"");

WriteLiteral("\r\n                     class=\"umeca-toast-error element-center\"");

WriteLiteral(">\r\n                    <p>");


#line 27 "HearingFormatList.cshtml"
                  Write(Model.message);


#line default
#line hidden
WriteLiteral("</p>\r\n                </div> \r\n            </div>\r\n        </div>\r\n");


#line 31 "HearingFormatList.cshtml"
}


#line default
#line hidden
WriteLiteral("<br />\r\n<div");

WriteLiteral(" id=\"toolbar2\"");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n    <a");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "javascript:newFormatoAudiencia(", true)

#line 34 "HearingFormatList.cshtml"
        , Tuple.Create<string,object,bool> ("", Model.CaseId

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ");", true)
);
WriteLiteral(">\r\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" id=\"btnAdd\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></i>\r\n    </button></a>\r\n</div>\r\n    <table");

WriteLiteral(" data-toggle=\"table\"");

WriteLiteral(" data-page-size=\"10\"");

WriteLiteral(" data-page-list=\"[10, 20, 30]\"");

WriteLiteral("\r\n     data-pagination=\"true\"");

WriteLiteral(" data-height=\"250\"");

WriteLiteral("\r\n     data-striped=\"true\"");

WriteLiteral(" data-search=\"true\"");

WriteLiteral(" \r\n     data-search-align=\"right\"");

WriteLiteral(" data-toolbar=\"#toolbar2\"");

WriteLiteral(@">
    <thead>
    <tr>
        <th>Carpeta de Investigaci&oacute;n</th>
        <th>Carpeta Judicial</th>
        <th>Nombre Completo</th>
        <th>Fecha de Registro</th>
        <th>Supervisor</th>
        <th>Audiencia</th>
        <th>Ampliaci&oacute;n de plazo</th>
        <th>Vinculaci&oacute;n a proceso</th>
        <th>Finalizado</th>
        <th>Acci&oacute;n</th>
    </tr>
    </thead>
    <tbody>
");


#line 58 "HearingFormatList.cshtml"
    

#line default
#line hidden

#line 58 "HearingFormatList.cshtml"
     foreach(var formatoAudiencia in Model.rows) {


#line default
#line hidden
WriteLiteral("    <tr");

WriteLiteral(" id=\"tr-id-1\"");

WriteLiteral(" class=\"tr-class-1\"");

WriteLiteral(">\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 61 "HearingFormatList.cshtml"
       Write(formatoAudiencia.IdFolder);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 64 "HearingFormatList.cshtml"
       Write(formatoAudiencia.IdMP);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 67 "HearingFormatList.cshtml"
       Write(formatoAudiencia.Fullname);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 70 "HearingFormatList.cshtml"
       Write(formatoAudiencia.RegisterTime);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 73 "HearingFormatList.cshtml"
       Write(formatoAudiencia.UserName);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 76 "HearingFormatList.cshtml"
       Write(formatoAudiencia.HearingType);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 79 "HearingFormatList.cshtml"
       Write(formatoAudiencia.Extension);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 82 "HearingFormatList.cshtml"
       Write(formatoAudiencia.ProcessVinc);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("       \t\t");


#line 85 "HearingFormatList.cshtml"
       Write(formatoAudiencia.FinishedStr);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");


#line 88 "HearingFormatList.cshtml"
        

#line default
#line hidden

#line 88 "HearingFormatList.cshtml"
         if(formatoAudiencia.IsFinished){


#line default
#line hidden
WriteLiteral("         \t<a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" style=\"display:inline-block;\"");

WriteLiteral(" title=\"Visualizar formatos de audiencia\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "visualizeFormat(", true)

#line 89 "HearingFormatList.cshtml"
                                                                                            , Tuple.Create<string,object,bool> ("", formatoAudiencia.CaseId

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ",", true)

#line 89 "HearingFormatList.cshtml"
                                                                                                                     , Tuple.Create<string,object,bool> ("", formatoAudiencia.Id

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ");", true)
);
WriteLiteral("><span");

WriteLiteral(" class=\"icon-eye-open\"");

WriteLiteral("></span></a>\r\n");


#line 90 "HearingFormatList.cshtml"
        }else{


#line default
#line hidden
WriteLiteral("         \t<a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" style=\"display:inline-block;\"");

WriteLiteral(" title=\"Visualizar formatos de audiencia\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "editFormatoAudiencia(", true)

#line 91 "HearingFormatList.cshtml"
                                                                                                 , Tuple.Create<string,object,bool> ("", formatoAudiencia.CaseId

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ",", true)

#line 91 "HearingFormatList.cshtml"
                                                                                                                          , Tuple.Create<string,object,bool> ("", formatoAudiencia.Id

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ");", true)
);
WriteLiteral("><span");

WriteLiteral(" class=\"icon-pencil\"");

WriteLiteral("></span></a>\r\n");


#line 92 "HearingFormatList.cshtml"
        }


#line default
#line hidden
WriteLiteral("        </td>\r\n    </tr>\r\n");


#line 95 "HearingFormatList.cshtml"
}


#line default
#line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n\t<!--<span class=\"btn btn-default btn-sm\" onclick=\"cancel" +
"ari();\">\r\n        Cancelar\r\n    </span>-->");

}
}
}
#pragma warning restore 1591
