#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmecaApp
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class JobUpsert : WebViewTemplate
{

#line hidden

#line 1 "JobUpsert.cshtml"
public UmecaApp.ModelContainer Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 3 "JobUpsert.cshtml"
  
Layout = "UmecaApp.headUm";


#line default
#line hidden
WriteLiteral("\r\n<script>\r\napp.controller(\'JobController\', function($scope, $timeout) {\r\n\t$scope" +
".m = {};\r\n    $scope.m.RelationshipId = {};\r\n    $scope.m.DocumentTypeId = {};\r\n" +
"    $scope.MsgError = \"\";\r\n\r\n    //anterior secundario actual\r\n    $scope.listRe" +
"gisterType=[];\r\n    $scope.RegisterType = {};\r\n    $scope.domTitle = \"\";\r\n\r\n    " +
"$scope.init = function(){\r\n\t\t    try{\r\n\t\t    \tconsole.log(\"modelContainer\"+$(\"#h" +
"dnJsonModelContainer\").val());\r\n\t\t    \tvar js = JSON.parse($(\"#hdnJsonModelConta" +
"iner\").val());\r\n\t\t\t    $scope.m = js;\r\n\t\t\t    var register = MeetingService.Regi" +
"sterTypeFindAllOrderByName();\r\n\t\t    \tconsole.log(\"register\"+register);\r\n\t\t    \t" +
"$scope.listRegisterType = JSON.parse(register);\r\n\t\t\t} catch(err){\r\n\t\t    \talert(" +
"\"Init erro==>\"+err.message);\r\n\t\t    }\r\n\t\t    if($scope.m.block == undefined ||$s" +
"cope.m.block == false ){\r\n\t\t    \t$scope.fillModel();\r\n\t\t    }\r\n\t\t    else{\r\n\t\t  " +
"  \t$scope.m.block = true;\r\n\t\t    }\r\n\t\t    //anterior actual secundario\r\n\t\t    if" +
"($scope.m.RegisterTypeId!=undefined && $scope.m.RegisterTypeId!=null && $scope.m" +
".RegisterTypeId!=0){\r\n\t\t    \t$scope.RegisterType = $scope.itemListById($scope.m." +
"RegisterTypeId , $scope.listRegisterType);\r\n\t\t    \t$scope.domTitle = $scope.Regi" +
"sterType[\'Name\'];\r\n\t\t    }\r\n\r\n\r\n\t\t    //fechas\r\n\t\tvar today  = new Date();\r\n    " +
"    var year = today.getFullYear();\r\n        var month = today.getMonth();\r\n    " +
"    var date = today.getDate();\r\n\r\n        if($scope.m.StartPrev == \"\" || $scope" +
".m.StartPrev == undefined){\r\n            $scope.m.StartPrev = year+\"/\"+(month+1)" +
"+\"/\"+date;\r\n        }\r\n        $scope.m.StartPrev= $scope.m.StartPrev.replace(/-" +
"/g,\"/\");\r\n        $scope.m.StartPrev = $scope.m.StartPrev.replace(\"T00:00:00\",\"\"" +
");\r\n        if($scope.m.Start == \"\" || $scope.m.Start == undefined){\r\n          " +
"  $scope.m.Start = year+\"/\"+(month+1)+\"/\"+date;\r\n        }\r\n        $scope.m.Sta" +
"rt= $scope.m.Start.replace(/-/g,\"/\");\r\n        $scope.m.Start = $scope.m.Start.r" +
"eplace(\"T00:00:00\",\"\");\r\n        if($scope.m.End == \"\" || $scope.m.End == undefi" +
"ned){\r\n            $scope.m.End = year+\"/\"+(month+1)+\"/\"+date;\r\n        }\r\n     " +
"   $scope.m.End= $scope.m.End.replace(/-/g,\"/\");\r\n        $scope.m.End = $scope." +
"m.End.replace(\"T00:00:00\",\"\");\r\n        //init schedule\r\n        if($scope.m.Sch" +
"edule!=undefined&&$scope.m.Schedule!=null){\r\n\t\t   \t$(\"#hdnJsonScheduleHome\").val" +
"($scope.m.Schedule);\r\n\t\t   \tconsole.log(\"hdnJsonScheduleHome-->\"+$(\"#hdnJsonSche" +
"duleHome\").val());\r\n\t    }\r\n\r\n\r\n    };\r\n\r\n    $timeout(function() {\r\n        $sc" +
"ope.init();\r\n    }, 0);\r\n\r\n    $scope.save = function(){\r\n    if($(\"#FormJobId\")" +
".valid() == false){\r\n         return false;\r\n    }else{\r\n    \t\t$scope.m.Schedule" +
" = $(\"#hdnJsonScheduleHome\").val();\r\n    \t\tconsole.log(\"save\"+$(\"#hdnMeetingCase" +
"Reference\").val());\r\n\t   \t\tvar jsonData = JSON.stringify($scope.m);\r\n\t\t\t$scope.m" +
"sgError = MeetingService.upsertLaboral(JSON.stringify($scope.m));\r\n\t\t\tif($scope." +
"msgError==undefined||$scope.msgError==null||$scope.msgError==\"\"){\r\n\t\t\t\t$scope.ca" +
"ncel($(\"#hdnMeetingCaseReference\").val());\r\n\t\t\t}\r\n\t}\r\n\t   };\r\n\r\n    $scope.cance" +
"l = function (idCase) {\r\n    console.log(\"cancel\"+idCase);\r\n        window.locat" +
"ion.replace(\'hybrid:Meeting/MeetingDatosPersonales?idCase=\'+idCase);\r\n    };\r\n\r\n" +
"    $scope.fillModel = function(){\r\n       var template= \"NO TRABAJA\";\r\n        " +
"//alert(\"en fill model con blcok \"+$scope.block);\r\n       if($scope.m.block == f" +
"alse){\r\n           $scope.m.Company= template;\r\n           $scope.m.Post= templa" +
"te;\r\n           $scope.m.Phone = template;\r\n           $scope.m.NameHead = templ" +
"ate;\r\n           $scope.m.ReasonChange = template;\r\n           $scope.m.Address=" +
" template;\r\n           for(var i= 0; i < $scope.listRegisterType.length ; i++){\r" +
"\n               if($scope.listRegisterType[i].Name == \"Anterior\"){\r\n            " +
"       $scope.RegisterType = $scope.listRegisterType[i];\r\n                   $sc" +
"ope.m.RegisterTypeId = $scope.listRegisterType[i].Id;\r\n                   $scope" +
".domTitle = $scope.RegisterType[\'Name\'];\r\n                   break;\r\n           " +
"    }\r\n           }\r\n       }else{\r\n           $scope.m.Company= \"\";\r\n          " +
" $scope.m.Post= \"\";\r\n           $scope.m.Phone = \"\";\r\n           $scope.m.NameHe" +
"ad = \"\";\r\n           $scope.m.ReasonChange = \"\";\r\n           $scope.m.Address = " +
"\"\";\r\n       }\r\n    };\r\n\r\n    $scope.itemListById = function(idObj, list){\r\n    \t" +
"console.log(\"idObj=\"+idObj);\r\n    \tif(idObj!=undefined&&idObj!=null){\r\n\t\t    for" +
"(x=0;x<list.length;x++){\r\n\t\t    \tif(list[x].Id==idObj){\r\n\t\t    \t\treturn list[x];" +
"\r\n\t\t    \t\tbreak;\r\n\t\t    \t}\r\n\t\t    }\r\n\t\t}\r\n\t\treturn undefined;\r\n\t};\r\n});\r\n</scrip" +
"t>\r\n<div>\r\n    <div");

WriteLiteral(" id=\"dlgUpModalId\"");

WriteLiteral(" ng-app=\"umecaMobile\"");

WriteLiteral(" ng-controller=\"JobController\"");

WriteLiteral(" >\r\n    <div>\r\n        <div");

WriteLiteral(" class=\"alert alert-info \"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</button>\r\n            <h4");

WriteLiteral(" class=\"element-center\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-briefcase\"");

WriteLiteral("></i>&nbsp;&nbsp;Empleo</h4>\r\n        </div>\r\n    </div>\r\n           \r\n<div>\r\n\t<d" +
"iv>\r\n\t    <input");

WriteLiteral(" id=\"hdnJsonModelContainer\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute ("value", " value=\"", "\""

#line 148 "JobUpsert.cshtml"
                     , Tuple.Create<string,object,bool> ("", Model.JsonModel

#line default
#line hidden
, false)
);
WriteLiteral(" name=\"jsonString\"");

WriteLiteral(" />\r\n\t    <input");

WriteLiteral(" id=\"hdnMeetingCaseReference\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute ("value", " value=\"", "\""

#line 149 "JobUpsert.cshtml"
                       , Tuple.Create<string,object,bool> ("", Model.Reference

#line default
#line hidden
, false)
);
WriteLiteral(" name=\"wasd\"");

WriteLiteral("/>\r\n\t</div>\r\n\t<form");

WriteLiteral(" id=\"FormJobId\"");

WriteLiteral(" name=\"FormJobId\"");

WriteLiteral(" >\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-12 element-center\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-6 element-right\"");

WriteLiteral(" >\r\n                &iquest;El imputado trabaja actualmente?\r\n            </div>\r" +
"\n            <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"block\"");

WriteLiteral("\r\n                       id=\"blockYes\"");

WriteLiteral(" ng-value=\"true\"");

WriteLiteral(" ng-model=\"m.block\"");

WriteLiteral(" ng-change=\"fillModel()\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"blockYes\"");

WriteLiteral(">Si</label> &nbsp;&nbsp;&nbsp;\r\n                <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral("  name=\"block\"");

WriteLiteral("\r\n                       id=\"blockNo\"");

WriteLiteral(" ng-value=\"false\"");

WriteLiteral(" ng-model=\"m.block\"");

WriteLiteral(" ng-change=\"fillModel()\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"blockNo\"");

WriteLiteral(">No</label>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"hr hr-3\"");

WriteLiteral("></div>\r\n    </div>\r\n    <br/>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-2 element-left\"");

WriteLiteral(">\r\n                Empresa:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-10\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"width-100\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("\r\n                       data-val=\"true\"");

WriteLiteral(" data-val-length=\"Debe tener al menos 3 y m&aacute;ximo 150 caracteres\"");

WriteLiteral("\r\n                       data-val-length-max=\"150\"");

WriteLiteral(" data-val-length-min=\"3\"");

WriteLiteral("   ng-readonly=\"!m.block\"");

WriteLiteral("\r\n                       data-val-required=\"El Nombre es un campo requerido\"");

WriteLiteral("\r\n                       name=\"Company\"");

WriteLiteral(" id=\"Company\"");

WriteLiteral(" ng-model=\"m.Company\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"Company\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n        </div>\r\n    </div>\r\n    </div>\r\n    <br/>\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Puesto:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral("\r\n                   data-val-length=\"Debe tener al menos 3 y m&aacute;ximo 50 ca" +
"racteres\"");

WriteLiteral("\r\n                   data-val-length-max=\"50\"");

WriteLiteral(" data-val-length-min=\"3\"");

WriteLiteral(" data-val-required=\"El puesto es un campo requerido\"");

WriteLiteral("\r\n                   ng-readonly=\"!m.block\"");

WriteLiteral("\r\n                   type=\"text\"");

WriteLiteral(" ng-model=\"m.Post\"");

WriteLiteral("\r\n                   name=\"post\"");

WriteLiteral(" id=\"post\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-9 col-xs-offset-3\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"post\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Tel&eacute;fono:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("  ng-readonly=\"!m.block\"");

WriteLiteral("\r\n                       data-val=\"true\"");

WriteLiteral(" data-val-length=\"Debe tener al menos 5 y m&aacute;ximo 200 caracteres\"");

WriteLiteral("\r\n                       data-val-length-max=\"200\"");

WriteLiteral(" data-val-length-min=\"5\"");

WriteLiteral("\r\n                       data-val-required=\"El tel&eacute;fono es un campo requer" +
"ido\"");

WriteLiteral("\r\n                       name=\"Phone\"");

WriteLiteral(" id=\"Phone\"");

WriteLiteral(" ng-model=\"m.Phone\"");

WriteLiteral(" ></textarea>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"Phone\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br/>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Nombre del patr&oacute;n:\r\n            </div>\r\n            <di" +
"v");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral("\r\n                   data-val-length=\"Debe tener al menos 6 y m&aacute;ximo 150 c" +
"aracteres\"");

WriteLiteral(" ng-readonly=\"!m.block\"");

WriteLiteral("\r\n                   data-val-length-max=\"150\"");

WriteLiteral(" data-val-length-min=\"6\"");

WriteLiteral("\r\n                   data-val-required=\"El nombre del patr&oacute;n es un campo r" +
"equerido\"");

WriteLiteral("\r\n                   type=\"text\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" ng-model=\"m.NameHead\"");

WriteLiteral("\r\n                   name=\"nameHead\"");

WriteLiteral(" id=\"nameHead\"");

WriteLiteral(">\r\n            </div>\r\n        \t<div");

WriteLiteral(" class=\"col-xs-10 col-xs-offset-1\"");

WriteLiteral(">\r\n           \t\t<span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"nameHead\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n        \t</div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-5 element-left\"");

WriteLiteral(">\r\n\t            Tipo de empleo:\r\n\t        </div>\r\n\t        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n\t            <select");

WriteLiteral(" class=\"form-control element-center\"");

WriteLiteral(" ng-model=\"RegisterType\"");

WriteLiteral("\r\n                ng-options=\"e.Name for e in listRegisterType\"");

WriteLiteral(" ng-readonly=\"!m.block\"");

WriteLiteral("\r\n                ng-change=\"m.RegisterTypeId = RegisterType[\'Id\']; domTitle = Re" +
"gisterType[\'Name\'];\"");

WriteLiteral(" ></select>\r\n\t        </div>\r\n        </div>\r\n    </div>\r\n    <br/>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" >\r\n        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-2 element-left\"");

WriteLiteral(">Direcci&oacute;n:</div>\r\n            <div");

WriteLiteral(" class=\"col-xs-10\"");

WriteLiteral(">\r\n                <textarea");

WriteLiteral(" id=\"address\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"address\"");

WriteLiteral(" ng-model=\"m.Address\"");

WriteLiteral(" ng-readonly=\"!m.block\"");

WriteLiteral("\r\n                          data-val=\"true\"");

WriteLiteral(" data-val-required=\"La direcci&oacute;n es un campo requerido\"");

WriteLiteral("\r\n                          data-val-length=\"Debe tener al menos 6 y m&aacute;xim" +
"o 500 caracteres\"");

WriteLiteral("\r\n                          data-val-length-max=\"500\"");

WriteLiteral(" data-val-length-min=\"6\"");

WriteLiteral("></textarea>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-xs-10 col-xs-offset-2\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"address\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n        </div>\r\n    </div>\r\n\r\n\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" ng-show=\"m.RegisterTypeId==3\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"widget-box\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"widget-header\"");

WriteLiteral(">\r\n            <h4>Trabajo {{domTitle}}</h4>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"widget-body\"");

WriteLiteral(">\r\n            <br/>\r\n\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-xs-10 col-xs-offset-1\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row widget-main\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n                            Fecha Inicio:\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" class=\"form-control date-picker\"");

WriteLiteral(" id=\"jdpStart\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("\r\n                                       data-date-format=\"yyyy/mm/dd\"");

WriteLiteral(" ng-model=\"m.StartPrev\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral("\r\n                                       data-val=\"true\"");

WriteLiteral(" data-val-required=\"La fecha de inicio es un campo requerido\"");

WriteLiteral("\r\n                                       name=\"startPrev\"");

WriteLiteral("/> <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i");

WriteLiteral(" class=\"icon-calendar bigger-110\"");

WriteLiteral("></i>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n                            </div>\r\n            " +
"                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-9 col-xs-offset-3\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"startPrev\"");

WriteLiteral("\r\n                                          data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n                                </div>\r\n                            </d" +
"iv>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n                            Fecha Fin:\r\n                        </div>\r\n      " +
"                  <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" class=\"form-control date-picker\"");

WriteLiteral(" id=\"jdbEnd\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("\r\n                                       data-date-format=\"yyyy/mm/dd\"");

WriteLiteral(" ng-model=\"m.End\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral("\r\n                                       data-val=\"true\"");

WriteLiteral(" data-val-required=\"La fecha de fin es un campo requerido\"");

WriteLiteral("\r\n                                       name=\"end\"");

WriteLiteral("/>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i");

WriteLiteral(" class=\"icon-calendar bigger-110\"");

WriteLiteral("></i>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n                            </div>\r\n\r\n          " +
"                  <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-9 col-xs-offset-3\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"end\"");

WriteLiteral("\r\n                                          data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n                                </div>\r\n                            </d" +
"iv>\r\n                        </div>\r\n                    </div>\r\n               " +
"     <br/>\r\n\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">Motivo de cambio:</div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-9\"");

WriteLiteral(">\r\n                            <textarea");

WriteLiteral(" id=\"form-field-11\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral("\r\n                                      ng-model=\"m.ReasonChange\"");

WriteLiteral(" name=\"reasonChange\"");

WriteLiteral(" ng-readonly=\"!m.block\"");

WriteLiteral("\r\n                                      data-val=\"true\"");

WriteLiteral("\r\n                                      data-val-required=\"El motivo de cambio es" +
" un campo requerido\"");

WriteLiteral(">{{m.ReasonChange}}</textarea>\r\n                        </div>\r\n                 " +
"   </div>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"reasonChange\"");

WriteLiteral("\r\n                              data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n                        <br/>\r\n\r\n                        <div");

WriteLiteral(" class=\"hr hr-8\"");

WriteLiteral("></div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n" +
"        </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" ng-show=\"m.RegisterTypeId == 1 || m.RegisterTypeId == 2\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"widget-box\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"widget-header\"");

WriteLiteral(">\r\n            <h4>Trabajo {{domTitle}}</h4>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"widget-body\"");

WriteLiteral(">\r\n            <br/>\r\n\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-xs-10 col-xs-offset-1\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n                            Fecha Inicio:\r\n                        </div>\r\n   " +
"                     <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" class=\"form-control date-picker\"");

WriteLiteral(" id=\"jdpStartCurrent\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("\r\n                                       data-date-format=\"yyyy/mm/dd\"");

WriteLiteral(" ng-model=\"m.Start\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral("\r\n                                       data-val=\"true\"");

WriteLiteral(" data-val-required=\"La fecha de inicio es un campo requerido\"");

WriteLiteral("\r\n                                       name=\"start\"");

WriteLiteral("/>\r\n                                                                    <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n                                                                        <i");

WriteLiteral(" class=\"icon-calendar bigger-110\"");

WriteLiteral("></i>\r\n                                                                    </span" +
">\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"start\"");

WriteLiteral("\r\n                                          data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n                                </div>\r\n                            </d" +
"iv>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n                            Salario semanal:\r\n                        </div>\r\n" +
"                        <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral("\r\n                                   data-val-length=\"Debe tener m&aacute;ximo 7 " +
"caracteres\"");

WriteLiteral(" name=\"salaryWeek\"");

WriteLiteral("\r\n                                   data-val-length-max=\"7\"");

WriteLiteral(" data-val-length-min=\"1\"");

WriteLiteral("\r\n                                   data-val-required=\"El salario semanal es un " +
"campo requerido\"");

WriteLiteral("\r\n                                   data-val-regex-pattern=\"([0-9]+(.[0-9])?)\"");

WriteLiteral("\r\n                                   data-val-regex=\"El salario s&oacute;lo puede" +
" contener n&uacute;meros y un punto\"");

WriteLiteral("\r\n                                   type=\"text\"");

WriteLiteral(" \r\n                                   ng-model=\"m.SalaryWeek\"");

WriteLiteral(">\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-xs-9 col-xs-offset-3\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"salaryWeek\"");

WriteLiteral("\r\n                                      data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n                            </div>\r\n                        </div>\r\n   " +
"                 </div>\r\n                    <br/>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n                    <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"widget-header header-color-blue\"");

WriteLiteral(">\r\n                                <h5");

WriteLiteral(" class=\"bigger lighter\"");

WriteLiteral(">\r\n                                    <h6><i");

WriteLiteral(" class=\"glyphicon glyphicon-calendar \"");

WriteLiteral("></i>Disponibilidad</h6>\r\n                                </h5>\r\n                " +
"            </div>\r\n\r\n                            <div");

WriteLiteral(" class=\"widget-body\"");

WriteLiteral(">\r\n<!--schedule component-->\r\n<div");

WriteLiteral(" id=\"divScheduleComponent\"");

WriteLiteral(">\r\n\r\n  <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"content/themes/umeca/bootstrap-timepicker.css\"");

WriteLiteral(" />\r\n  <script");

WriteLiteral(" src=\"scripts/umeca/date-time/bootstrap-datepicker.min.js\"");

WriteLiteral("></script>\r\n  <script");

WriteLiteral(" src=\"scripts/umeca/date-time/moment.min.js\"");

WriteLiteral("></script>\r\n  <script");

WriteLiteral(" src=\"scripts/app/shared/dateTimePickerCursor.js\"");

WriteLiteral("></script>\r\n  <script");

WriteLiteral(" src=\"scripts/app/reviewer/scheduleCtrl2.js\"");

WriteLiteral("></script>\r\n\r\n  <div");

WriteLiteral(" class=\"row element-center\"");

WriteLiteral(" ng-controller=\"scheduleController\"");

WriteLiteral(" id=\"divComponentSchedule\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" ng-model=\"schString\"");

WriteLiteral(" name=\"sch\"");

WriteLiteral(" id=\"hdnJsonScheduleHome\"");

WriteLiteral(" ng-update-hidden");

WriteLiteral(" ng-init=\"\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" ng-model=\"content\"");

WriteLiteral(" ng-init=\"content =\'\'+\'Home\';\"");

WriteLiteral(" ng-update-hidden >\r\n    <div");

WriteLiteral(" class=\"col-xs-10 col-xs-offset-1\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-4 element-center\"");

WriteLiteral(">\r\n         D&iacute;a(s)<br/>\r\n         <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" value=\"\"");

WriteLiteral("\r\n         ng-model=\"s.Day\"");

WriteLiteral(" ng-init=\'s.Day= \"\"\'");

WriteLiteral(">\r\n       </div>\r\n       <div");

WriteLiteral(" class=\"col-xs-3 element-center\"");

WriteLiteral(">\r\n        Inicio<br/>\r\n        <div");

WriteLiteral(" class=\"input-group bootstrap-timepicker\"");

WriteLiteral(">\r\n          <input");

WriteLiteral(" id=\"timepickerStart{{content}}\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control umeca-time-picker tp\"");

WriteLiteral(" ng-model=\"s.Start\"");

WriteLiteral("/>\r\n          <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"icon-time bigger-60\"");

WriteLiteral("></i>\r\n          </span>\r\n        </div>\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-xs-3 element-center\"");

WriteLiteral(">\r\n        Fin <br/>\r\n        <div");

WriteLiteral(" class=\"input-group bootstrap-timepicker\"");

WriteLiteral(">\r\n          <input");

WriteLiteral(" id=\"timepickerEnd{{content}}\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control umeca-time-picker tp\"");

WriteLiteral(" ng-model=\"s.End\"");

WriteLiteral("/>\r\n          <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"icon-time  bigger-40\"");

WriteLiteral("></i>\r\n          </span>\r\n        </div>\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n        Acciones<br/><div");

WriteLiteral(" class=\"space-5\"");

WriteLiteral("></div>\r\n        <i");

WriteLiteral(" class=\"icon-plus-sign orange\"");

WriteLiteral(" style=\"cursor:pointer;\"");

WriteLiteral(" ng-click=\"addSchedule()\"");

WriteLiteral(">  </i>\r\n      </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"hr hr-6\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" ng-show=\"msgError\"");

WriteLiteral(" class=\"alert-danger element-center\"");

WriteLiteral(">\r\n      {{msgError}}\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(" ng-show=\"listSchedule.length==0\"");

WriteLiteral(">\r\n      <br/>\r\n      <br/>\r\n      <br/>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-xs-9 col-xs-offset-1\"");

WriteLiteral(" ng-show =\"listSchedule.length > 0\">\r\n     <div");

WriteLiteral(" class=\"row center\"");

WriteLiteral(">\r\n       <div");

WriteLiteral(" class=\"col-xs-5\"");

WriteLiteral(">\r\n         <h5");

WriteLiteral(" class=\"smaller lighter blue\"");

WriteLiteral(">D&iacute;a</h5>\r\n         <div");

WriteLiteral(" class=\"hr hr-2\"");

WriteLiteral("></div>\r\n       </div>\r\n       <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n         <h5");

WriteLiteral(" class=\"smaller lighter blue\"");

WriteLiteral(">Inicio</h5>\r\n         <div");

WriteLiteral(" class=\"hr hr-2\"");

WriteLiteral("></div>\r\n       </div>\r\n       <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n         <h5");

WriteLiteral(" class=\"smaller lighter blue\"");

WriteLiteral(">Fin</h5>\r\n         <div");

WriteLiteral(" class=\"hr hr-2\"");

WriteLiteral("></div>\r\n       </div>\r\n       <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n         <h5");

WriteLiteral(" class=\"smaller lighter blue\"");

WriteLiteral(">Acciones</h5>\r\n         <div");

WriteLiteral(" class=\"hr hr-2\"");

WriteLiteral("></div>\r\n       </div>\r\n     </div>\r\n     <div");

WriteLiteral(" class=\"row center\"");

WriteLiteral(" ng-repeat =\"sch in listSchedule track by $index\">\r\n      <div");

WriteLiteral(" class=\"col-xs-5\"");

WriteLiteral(">\r\n        {{sch.Day}}\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n       {{sch.Start}}\r\n     </div>\r\n     <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n      {{sch.End}}\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n      <i");

WriteLiteral(" class=\"icon-trash red\"");

WriteLiteral(" style=\"cursor:pointer;\"");

WriteLiteral(" ng-click=\"deleteSchedule($index)\"");

WriteLiteral(@"></i>
    </div>
  </div>
  <br/>
</div>
</div>
<br/>
</div>
</div>
            <!--schedule component-->
                        </div>








                    </div>
                    <br/>
                </div>
            </div>
        </div>
    </div>
</div>






</div>

                    <br />
                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" ng-show=\"MsgError\"");

WriteLiteral(" class=\"alert alert-danger element-center\"");

WriteLiteral(">\r\n                                {{MsgError}}\r\n                            </di" +
"v>\r\n                        </div>\r\n                    </div>\r\n                " +
"\r\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"btn btn-default btn-sm\"");

WriteAttribute ("ng-click", "  ng-click=\"", "\""
, Tuple.Create<string,object,bool> ("", "cancel(\'", true)

#line 542 "JobUpsert.cshtml"
                                     , Tuple.Create<string,object,bool> ("", Model.Reference

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\')", true)
);
WriteLiteral(">\r\n                        Cancelar\r\n                    </span>\r\n               " +
"     <span");

WriteLiteral(" class=\"btn btn-default btn-primary btn-sm\"");

WriteLiteral("\r\n                           ng-click=\"save();\"");

WriteLiteral(@">
                          Guardar
                    </span>
                </div>
                </form>
                </div>
            </div>

<script>
    $('.date-picker').datepicker({autoclose:true, endDate:new Date()}).next().on(ace.click_event, function(){
        $(this).prev().focus();
    });
</script>");

}
}
}
#pragma warning restore 1591
