#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmecaApp
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class LogActivityList : WebViewTemplate
{

#line hidden

#line 1 "LogActivityList.cshtml"
public UmecaApp.LogActivityListDto Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 4 "LogActivityList.cshtml"
   
	Layout = "UmecaApp.HeadSupervition";


#line default
#line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    function newLogActivity(fuente){\r\n\t\twindow.location.replace(\'hybrid:Superv" +
"ision/AddCaseLog?idCase=\'+fuente);\r\n    }\r\n    </script>\r\n<h2");

WriteLiteral(" class=\"element-center\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-comments-alt \"");

WriteLiteral("></i>&nbsp;&nbsp;Bitácora del caso</h2>\r\n");


#line 13 "LogActivityList.cshtml"
 if(Model.message!=null){


#line default
#line hidden
WriteLiteral("\t\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" onclick=\"javascript:$(this).hide();\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" msg=\"MsgError\"");

WriteLiteral("\r\n                     class=\"umeca-toast-error element-center\"");

WriteLiteral(">\r\n                    <p>");


#line 18 "LogActivityList.cshtml"
                  Write(Model.message);


#line default
#line hidden
WriteLiteral("</p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n");


#line 22 "LogActivityList.cshtml"
}


#line default
#line hidden
WriteLiteral("<br />\r\n<table");

WriteLiteral(" class=\"tableInfo\"");

WriteLiteral(">\r\n    <tr>\r\n        <td");

WriteLiteral(" class=\"labelInfo\"");

WriteLiteral(">IMPUTADO</td>\r\n        <td");

WriteLiteral(" class=\"fieldInfo\"");

WriteLiteral(">");


#line 27 "LogActivityList.cshtml"
                         Write(Model.imputado);


#line default
#line hidden
WriteLiteral("</td>\r\n    </tr>\r\n    <tr>\r\n        <td");

WriteLiteral(" class=\"labelInfo\"");

WriteLiteral(">Carpeta Judicial</td>\r\n        <td");

WriteLiteral(" class=\"fieldInfo\"");

WriteLiteral(">");


#line 31 "LogActivityList.cshtml"
                         Write(Model.folder);


#line default
#line hidden
WriteLiteral("</td>\r\n    </tr>\r\n</table>\r\n\r\n<br/>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n   <div");

WriteLiteral(" class=\"col-xs-6 align-left\"");

WriteLiteral(">\r\n       <i");

WriteLiteral(" class=\"glyphicon glyphicon-plus-sign purple\"");

WriteLiteral(">&nbsp; </i><a");

WriteLiteral(" href=\"#\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "newLogActivity(", true)

#line 38 "LogActivityList.cshtml"
                                                               , Tuple.Create<string,object,bool> ("", Model.CaseId

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ")", true)
);
WriteLiteral(">Agrgar actividad espont&aacute;nea</a>\r\n   </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"panel panel-default panel-primary\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(" ng-init=\'listLog=${listLog};\'");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"icon-tasks\"");

WriteLiteral("></span>&nbsp;&nbsp;LISTADO DE ACTIVIDADES\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"widget-box transparent\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"widget-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"widget-main no-padding\"");

WriteLiteral(">\r\n                        <table");

WriteLiteral(" class=\"table table-bordered table-striped\"");

WriteLiteral(">\r\n                            <thead");

WriteLiteral(" class=\"thin-border-bottom\"");

WriteLiteral(">\r\n                            <tr>\r\n                                <th");

WriteLiteral(" class=\"col-xs-2 element-center\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"icon-caret-right blue\"");

WriteLiteral("></i>\r\n                                    FECHA Y HORA\r\n                        " +
"        </th>\r\n\r\n                                <th");

WriteLiteral(" class=\"col-xs-2 element-center\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"icon-caret-right blue\"");

WriteLiteral("></i>\r\n                                    ACTIVIDAD\r\n                           " +
"     </th>\r\n                                <th");

WriteLiteral(" class=\"col-xs-2 element-center\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"icon-caret-right blue\"");

WriteLiteral("></i>\r\n                                    REALIZADO POR\r\n                       " +
"         </th>\r\n                                <th");

WriteLiteral(" class=\"col-xs-6 element-center\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"icon-caret-right blue\"");

WriteLiteral("></i>\r\n                                    DETALLES\r\n                            " +
"    </th>\r\n                            </tr>\r\n                            </thea" +
"d>\r\n\r\n                            <tbody>\r\n");


#line 75 "LogActivityList.cshtml"
                            

#line default
#line hidden

#line 75 "LogActivityList.cshtml"
                             foreach(var logRow in Model.rows) {


#line default
#line hidden
WriteLiteral("                            <tr>\r\n                                <td><span>");


#line 77 "LogActivityList.cshtml"
                                     Write(logRow.dateString);


#line default
#line hidden
WriteLiteral("</span></td>\r\n                                <td><span>");


#line 78 "LogActivityList.cshtml"
                                     Write(logRow.activity);


#line default
#line hidden
WriteLiteral("</span>\r\n                                </td>\r\n                                <" +
"td><span>");


#line 80 "LogActivityList.cshtml"
                                     Write(logRow.userName);


#line default
#line hidden
WriteLiteral("</span></td>\r\n                                <td");

WriteLiteral(" class=\"align-left\"");

WriteLiteral("><strong><span");

WriteLiteral(" class=\"text-primary\"");

WriteLiteral(">");


#line 81 "LogActivityList.cshtml"
                                                                                     Write(logRow.title);


#line default
#line hidden
WriteLiteral("</span></strong><br/>\r\n                                    <span>");


#line 82 "LogActivityList.cshtml"
                                     Write(logRow.resume);


#line default
#line hidden
WriteLiteral("</span>\r\n                                </td>\r\n                            </tr>" +
"\r\n");


#line 85 "LogActivityList.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                            </tbody>\r\n                        </table>\r\n         " +
"           </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n " +
"   </div>\r\n</div>\r\n");

}
}
}
#pragma warning restore 1591
