#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmecaApp
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class MeetingList : WebViewTemplate
{

#line hidden

#line 1 "MeetingList.cshtml"
public UmecaApp.MeetingTblDto Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 3 "MeetingList.cshtml"
  
	Layout = "UmecaApp.headUmGrid";


#line default
#line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    function tblAfterLoadIcons(){\r\n        var tblData = $(\'#table2\').bootstra" +
"pTable(\'getData\',null);\r\n        console.log(\"typeof tblData_>\"+typeof tblData+\"" +
"  printed tblData-->\"+tblData);\r\n        if(tblData.length!=undefined&&tblData.l" +
"ength>=1){\r\n            if(tblData[0].statusCode==undefined||tblData[0].statusCo" +
"de==null){\r\n                 \r\n            }\r\n            else{\r\n               " +
" for(var i=0;i<tblData.length;i++){\r\n                    var be=\"\";\r\n           " +
"         if ( tblData[i].statusCode == \'INCOMPLETE_LEGAL\') {\r\n                  " +
"      be = \"<a href=\\\"javascript:;\\\" style=\\\"display:inline-block;\\\" title=\\\"Pro" +
"cesos legales usuario\\\" onclick=\\\"window.legal(\'\" + i + \"\');\\\"><i class=\\\"icon-l" +
"egal\\\"></i></a>\";\r\n                    }else if(tblData[i\r\n                    ]" +
".statusCode == \'INCOMPLETE\'){\r\n                        be = \"<a href=\\\"javascrip" +
"t:;\\\" style=\\\"display:inline-block;\\\" title=\\\"Continuar entrevista\\\" onclick=\\\"w" +
"indow.upsert(\'\" + i + \"\');\\\"><span class=\\\"glyphicon glyphicon-pencil\\\"></span><" +
"/a>\";\r\n                    }\r\n                    tblData[i].Action=be;\r\n       " +
"         }\r\n                    $(\'#table2\').bootstrapTable(\'load\',tblData);\r\n  " +
"          }\r\n        }\r\n    }\r\n    function afterDrawTbl(){\r\n    setTimeout(tblA" +
"fterLoadIcons(), 100);\r\n    }\r\n    function legal(err){\r\n    \talert(\"cosa>>\"+err" +
");\r\n    }\r\n    function editMeeting(err){\r\n    \talert(\"cosa2>>\"+err);\r\n    }\r\n  " +
"  function cancelari(){\r\n\t\twindow.location.replace(\'hybrid:Login/Index\');\r\n    }" +
"\r\n    </script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
/*$( document ).ready(function() {
    console.log( ""ready!"" );
     
        //tabla dos todo mendiante javascript 

        //didnt find """"sorttype: 'string', searchoptions: { sopt: ['bw'] } }""""
      $('#table2').bootstrapTable({
        pageSize: 10,
        pageList: [10, 20, 30],    //si pagination es true muestra el selector de numero de registros por pagina justo al lado de el texto de mostrando
        pagination: true,   //numero de registros, numero de registros por pagina, paginador
        height: 450,
        //NOT AVAIBLE:>shrinkToFit: false,
        //NOT AVAIBLE:>caption: ""&nbsp;"",
        striped: true,   //altRows: true,
        search: true,       //campo de buscar, busca en todas las columnas excepto las marcadas con ""searchable: false""
        searchAlign: 'right',    //de que lado aparecera el input de busqueda ""left|rigth""
        toolbar: '#toolbar2',            //selector de jquery para indicarle cual es la toolbar
        onLoadSuccess: afterDrawTbl()
		});
});*/
</script>
<h2");

WriteLiteral(" class=\"element-center\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-comments-alt \"");

WriteLiteral("></i>&nbsp;&nbsp;Entrevistas de evaluaci&oacute;n de riesgos procesales</h2>\r\n<br" +
" />\r\n<table");

WriteLiteral(" id=\"table2\"");

WriteLiteral(">\r\n\r\n\t\t</table>\r\n\r\n\t\t<br /><br /><br />\r\n\r\n\r\n<div");

WriteLiteral(" id=\"toolbar2\"");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n    <a");

WriteAttribute ("href", " href=\"", "\""

#line 74 "MeetingList.cshtml"
, Tuple.Create<string,object,bool> ("", Url.Action("MeetingEditNew","Meeting")

#line default
#line hidden
, false)
);
WriteLiteral(">\r\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" id=\"btnAdd\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></i>\r\n    </button></a>\r\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" id=\"btnRefresh\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"glyphicon glyphicon-refresh\"");

WriteLiteral("></i>\r\n    </button>\r\n</div>\r\n\r\n\r\n    <table");

WriteLiteral(" data-toggle=\"table\"");

WriteLiteral(" data-page-size=\"10\"");

WriteLiteral(" data-page-list=\"[10, 20, 30]\"");

WriteLiteral("\r\n     data-pagination=\"true\"");

WriteLiteral(" data-height=\"450\"");

WriteLiteral("\r\n     data-striped=\"true\"");

WriteLiteral(" data-search=\"true\"");

WriteLiteral(" \r\n     data-search-align=\"right\"");

WriteLiteral(" data-toolbar=\"#toolbar2\"");

WriteLiteral(">\r\n    <thead>\r\n    <tr>\r\n        <th>ID</th>\r\n        <th");

WriteLiteral(" data-width=\"900\"");

WriteLiteral(@">Carpeta de Investigaci&oacute;n</th>
        <th>Nombre completo</th>
        <th>Fecha de nacimiento</th>
        <th>G&eacute;nero</th>
        <th>Estatus</th>
        <!--<th>Id estatus</th>
        <th>Status case</th>-->
        <th>Acci&oacute;n</th>
    </tr>
    </thead>
    <tbody>
    <tr");

WriteLiteral(" id=\"tr-id-1\"");

WriteLiteral(" class=\"tr-class-1\"");

WriteLiteral(">\r\n        <td");

WriteLiteral(" id=\"td-id-1\"");

WriteLiteral(" class=\"td-class-1\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");


#line 104 "MeetingList.cshtml"
       Write(Model.CaseId);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 107 "MeetingList.cshtml"
    Write(Model.IdFolder);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 110 "MeetingList.cshtml"
     Write(Model.Name+" "+Model.LastNameP+" "+Model.LastNameM);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 113 "MeetingList.cshtml"
     Write(((DateTime) Model.DateBirth).ToString("yyyy/MM/dd"));


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td");

WriteLiteral(" id=\"td-id-1\"");

WriteLiteral(" class=\"td-class-1\"");

WriteLiteral(">\r\n");


#line 116 "MeetingList.cshtml"
            

#line default
#line hidden

#line 116 "MeetingList.cshtml"
             if (Model.Gender != null) {
                        if (Model.Gender.Equals(true)){//true is female


#line default
#line hidden
WriteLiteral("                        \t<label>Femenino</label>\r\n");


#line 119 "MeetingList.cshtml"
                        }else{


#line default
#line hidden
WriteLiteral("                            <label>Masculino</label>\r\n");


#line 121 "MeetingList.cshtml"
                        }
                    } else {


#line default
#line hidden
WriteLiteral("                        <label>Sin proporcionar</label>\r\n");


#line 124 "MeetingList.cshtml"
                    }


#line default
#line hidden
WriteLiteral("        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 127 "MeetingList.cshtml"
    Write(Model.Description);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <!--<td>\r\n");

WriteLiteral("       \t\t");


#line 130 "MeetingList.cshtml"
    Write(Model.StatusCode);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 133 "MeetingList.cshtml"
    Write(Model.ReviewerId);


#line default
#line hidden
WriteLiteral("\r\n        </td>-->\r\n        <td>\r\n");


#line 136 "MeetingList.cshtml"
         

#line default
#line hidden

#line 136 "MeetingList.cshtml"
          if(Model.StatusCode=="INCOMPLETE_LEGAL") {


#line default
#line hidden
WriteLiteral("         \t<a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" style=\"display:inline-block;\"");

WriteLiteral(" title=\"Procesos legales usuario\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "legal(", true)

#line 137 "MeetingList.cshtml"
                                                                        , Tuple.Create<string,object,bool> ("", Model.Action

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ");", true)
);
WriteLiteral("><i");

WriteLiteral(" class=\"icon-legal\"");

WriteLiteral("></i></a>\r\n");


#line 138 "MeetingList.cshtml"
         }
         else if(Model.StatusCode=="INCOMPLETE") {


#line default
#line hidden
WriteLiteral("         \t<a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" style=\"display:inline-block;\"");

WriteLiteral(" title=\"Continuar entrevista\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "editMeeting(", true)

#line 140 "MeetingList.cshtml"
                                                                          , Tuple.Create<string,object,bool> ("", Model.Action

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ");", true)
);
WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-pencil\"");

WriteLiteral("></span></a>\r\n");


#line 141 "MeetingList.cshtml"
         }


#line default
#line hidden
WriteLiteral("        </td>\r\n    </tr>\r\n    </tbody>\r\n</table>\r\n\r\n    <span");

WriteLiteral(" class=\"btn btn-default btn-sm\"");

WriteLiteral(" onclick=\"cancelari();\"");

WriteLiteral(@">
                        Cancelar
                    </span>

<script>
    var $table = $('#table2');
       //onload
    $(function () {
         $button = $('#btnAdd');
          $button2 = $('#btnRefresh');
           $button3 = $('#btnExport');
        $button.click(function () {
            console.log(""cliked agregar"");
            tblAfterLoadIcons();
        });
        $button2.click(function () {
            console.log(""cliked recargar"");
        });
        $button3.click(function () {
            console.log(""cliked exportar"");
        });
    }); 

</script>");

}
}
}
#pragma warning restore 1591
