#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmecaApp
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class NewLogActivity : WebViewTemplate
{

#line hidden

#line 1 "NewLogActivity.cshtml"
public Umeca.Data.LogCase Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 4 "NewLogActivity.cshtml"
  
	Layout = "UmecaApp.HeadSupervition";


#line default
#line hidden
WriteLiteral("\r\n\r\n  <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"content/themes/umeca/bootstrap-timepicker.css\"");

WriteLiteral(" />\r\n  <script");

WriteLiteral(" src=\"scripts/umeca/date-time/bootstrap-datepicker.min.js\"");

WriteLiteral("></script>\r\n  <script");

WriteLiteral(" src=\"scripts/umeca/date-time/moment.min.js\"");

WriteLiteral("></script>\r\n  <script");

WriteLiteral(" src=\"scripts/app/shared/dateTimePickerCursor.js\"");

WriteLiteral("></script>\r\n<script>\r\n    \tapp.controller(\'newLogActivityController\', function($s" +
"cope, $http, $timeout){\r\n\t\t\t$scope.m = {};\r\n\t\t\t$scope.v = {};\r\n\t\t\t$scope.Wait = " +
"false;\r\n\t\t\t$scope.lstRel = [];\r\n\t\t\t$scope.iden = [];\r\n\r\n\t\t\t$timeout(function() {" +
"\r\n\t\t        $scope.init();\r\n\t\t    }, 0);\r\n\r\n\t\t\t$scope.init = function(){\r\n\t\t\tvar" +
" relaciones = MeetingService.findAllRelationship();\r\n\t\t    console.log(\"relacion" +
"es\"+relaciones);\r\n\t\t    $scope.lstRel = JSON.parse(relaciones);\r\n\r\n\t\t    var doc" +
"umentos = MeetingService.findAllDocumentType();\r\n\t\t    console.log(\"documentos\"+" +
"documentos);\r\n\t\t    $scope.lstDoc = JSON.parse(documentos);\r\n\t\t\t}\r\n\r\n\r\n\r\n\t\t\t$sco" +
"pe.save = function(){\r\n\t\t\t\t$scope.Wait = true;\r\n\r\n\r\n\r\n\t\t\t\t//todos los key del js" +
"on deben ser igual al modelo cs\r\n\t\t\t\tif($(\"#frmSubmitValuesCaseLog\").valid()==fa" +
"lse){\r\n\t\t\t\t\t$scope.Wait = false;\r\n\t\t\t\t\treturn false;\r\n\t\t\t\t}\r\n\t\t\t\t$scope.m.caseDe" +
"tentionId = $(\"#caseDetentionId\").val();\r\n\t\t\t\t$scope.m.activity = $(\"#activity\")" +
".val();\r\n\t\t\t\t$scope.m.userId = $(\"#userId\").val();\r\n\t\t\t\t$scope.m.activityString " +
"= $(\"#activityString\").val();\r\n\t\t\t\tconsole.log(\"1\");\r\n\t\t\t\tvar arrBth = [];\r\n    " +
"            arrBth = $scope.v.Start.split(\'/\');\r\n                console.log(\"2\"" +
");\r\n                var taim = [];\r\n                taim = $scope.v.TStart.split" +
"(\':\');\r\n                var d;\r\n                if (arrBth.length > 0 && taim.le" +
"ngth > 0){\r\n\t\t\t\t\td = new Date(parseInt(arrBth[0]), parseInt(arrBth[1]) - 1, pars" +
"eInt(arrBth[2]),taim[0],taim[1],\"00\");\r\n\t\t\t\t}\r\n\t\t\t\tconsole.log(\"3\");\r\n\t\t\t\t$scope" +
".m.date = d ;\r\n\t\t\t\tif($scope.v.Dirigido!=\"la Víctima o testigo\"||$scope.v.Dirigi" +
"do!=\"la Fuente,\"){\r\n\t\t\t\t\t$scope.v.Relationship = \"\";\r\n\t\t\t\t}else{\r\n\t\t\t\t$scope.v.R" +
"elationship += \",\";\r\n\t\t\t\t}\r\n\t\t\t\tif($scope.v.Dirigido == \"el Imputado,\"){\r\n\t\t\t\t$s" +
"cope.v.Despecify = \"\";\r\n\t\t\t\t}\r\n\t\t\t\tconsole.log(\"4\");\r\n\t\t\t\t$scope.m.title = \"Visi" +
"ta Domiciliar \"+$scope.v.Tipoa+\" a \"+$scope.v.Dirigido+\" \"+$scope.v.Relationship" +
"+\" \"+$scope.v.Despecify+\" en la dirección: \"+$scope.v.Direcci+\", con el objetivo" +
" de \"+$scope.v.Objetivo+\".\";\r\n\t\t\t\t$scope.m.resume = \"Información proporcionada:\"" +
"+$scope.v.Info+\"  Observaciones del supervisor: \"+$scope.v.Observacion+\"  Identi" +
"ficación presentada: \"+$scope.v.Identity;\r\n\t\t\t\tconsole.log(\"title\"+$scope.m.titl" +
"e);\r\n\t\t\t\tconsole.log(\"resume\"+$scope.m.resume);\r\n\t\t\t\tvar jsonData = JSON.stringi" +
"fy($scope.m);\r\n\t\t\t\tvar resultado = SupervisionService.upsertLogCase(jsonData);\r\n" +
"\t\t\t\tif(resultado==undefined||resultado==null||resultado==\"\"){\r\n\t\t\t\t\twindow.locat" +
"ion.replace(\'hybrid:Supervision/LogActivityLst?idCase=\'+$scope.m.caseDetentionId" +
");\r\n\t\t\t\t}else{\r\n\t\t\t\t\talert(resultado);\r\n\t\t\t\t}\r\n\t\t\t\t$scope.Wait = false;\r\n\t\t\t};\r\n" +
"\r\n\t\t\t$scope.cancel = function(caso){\r\n\t\t\t\t//todos los key del json deben ser igu" +
"al al modelo cs\r\n\t\t\t\twindow.location.replace(\'hybrid:Supervision/LogActivityLst?" +
"idCase=\'+caso);\r\n\t\t\t};\r\n\r\n\t\t});\r\n    </script>\r\n<form");

WriteLiteral(" id=\"frmSubmitValuesCaseLog\"");

WriteLiteral(" ng-app=\"umecaMobile\"");

WriteLiteral(" ng-controller=\"newLogActivityController\"");

WriteLiteral(">\r\n\r\n   \t<div");

WriteLiteral(" class=\"alert alert-info \"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">×</button>\r\n        <h4");

WriteLiteral(" class=\"element-center\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-asterisk \"");

WriteLiteral("></i>&nbsp;&nbsp;Agregar actividad espontánea</h4>\r\n    </div>\r\n    <br>\r\n    <in" +
"put");

WriteLiteral(" type=\"hidden\"");

WriteAttribute ("value", " value=\"", "\""

#line 99 "NewLogActivity.cshtml"
, Tuple.Create<string,object,bool> ("", Model.caseDetentionId

#line default
#line hidden
, false)
);
WriteLiteral(" id=\"caseDetentionId\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute ("value", " value=\"", "\""

#line 100 "NewLogActivity.cshtml"
, Tuple.Create<string,object,bool> ("", Model.activity

#line default
#line hidden
, false)
);
WriteLiteral(" id=\"activity\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute ("value", " value=\"", "\""

#line 101 "NewLogActivity.cshtml"
, Tuple.Create<string,object,bool> ("", Model.userId

#line default
#line hidden
, false)
);
WriteLiteral(" id=\"userId\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute ("value", " value=\"", "\""

#line 102 "NewLogActivity.cshtml"
, Tuple.Create<string,object,bool> ("", Model.activityString

#line default
#line hidden
, false)
);
WriteLiteral(" id=\"activityString\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n\t\t    <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n\t\t        Fecha de la visita:\r\n\t\t    </div>\r\n\t\t    <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n\t\t        <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n\t\t            <input");

WriteLiteral(" class=\"form-control date-picker\"");

WriteLiteral(" id=\"jdpStartCurrent\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("\r\n\t\t                   data-date-format=\"yyyy/mm/dd\"");

WriteLiteral(" ng-model=\"v.Start\"");

WriteLiteral("\r\n\t\t                   data-val=\"true\"");

WriteLiteral(" data-val-required=\"La fecha de la visita es un campo requerido\"");

WriteLiteral("\r\n\t\t                   name=\"start\"");

WriteLiteral("/>\r\n\t\t                                                <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n\t\t                                                    <i");

WriteLiteral(" class=\"icon-calendar bigger-110\"");

WriteLiteral("></i>\r\n\t\t                                                </span>\r\n\t\t        </div" +
">\r\n\t\t        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n\t\t                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"start\"");

WriteLiteral("\r\n\t\t                      data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n\t\t            </div>\r\n\t\t        </div>\r\n\t\t    </div>\r\n\t\t</div>\r\n\t</div>" +
"\r\n    <br />\r\n\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n\t\t    <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n\t        \tHora de la visita:\r\n\t        </div>\r\n\t        <div");

WriteLiteral(" class=\"col-xs-8 input-group bootstrap-timepicker\"");

WriteLiteral(">\r\n\t          <input");

WriteLiteral(" id=\"timepickerStart\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control umeca-time-picker tp\"");

WriteLiteral(" ng-model=\"v.TStart\"");

WriteLiteral("\r\n\t           data-val=\"true\"");

WriteLiteral(" data-val-required=\"La fecha de la visita es un campo requerido\"");

WriteLiteral(" name=\"tstatr\"");

WriteLiteral("/>\r\n\t          <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(">\r\n\t            <i");

WriteLiteral(" class=\"icon-time bigger-60\"");

WriteLiteral("></i>\r\n\t          </span>\r\n\t        </div>\r\n\t\t    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n\t\t            <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"tstatr\"");

WriteLiteral("\r\n\t\t                  data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n\t\t        </div>\r\n\t\t    </div>\r\n\t\t</div>\r\n\t</div>\r\n\t<br />\r\n\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                La actividad es:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"v.Tipoa\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-required=\"El Tipo de actividad es un campo requerido\"");

WriteLiteral("\r\n\t                       name=\"Tipoa\"");

WriteLiteral(" >\r\n\t\t\t\t\t<option");

WriteLiteral(" value=\"programada\"");

WriteLiteral(">Programada</option>\r\n\t\t\t\t\t<option");

WriteLiteral(" value=\"emergente\"");

WriteLiteral(">Emergente</option>\r\n\t\t\t\t</select>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"Tipoa\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br />\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Dirigido a:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n            <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"v.Dirigido\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-required=\"El Objetivo es un campo requerido\"");

WriteLiteral("\r\n                       name=\"Dirigido\"");

WriteLiteral(" >\r\n\t\t\t\t<option");

WriteLiteral(" value=\"el Imputado,\"");

WriteLiteral(">Imputado</option>\r\n\t\t\t\t<option");

WriteLiteral(" value=\"la Víctima o testigo\"");

WriteLiteral(">Víctima o testigo</option>\r\n\t\t\t\t<option");

WriteLiteral(" value=\"la Fuente,\"");

WriteLiteral(">Fuente</option>\r\n\t\t\t\t<option");

WriteLiteral(" value=\"la Institución pública o privada,\"");

WriteLiteral(">Institución pública o privada</option>\r\n\t\t\t\t<option");

WriteLiteral(" value=\"otro,\"");

WriteLiteral(">Otro</option>\r\n\t\t\t</select>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"Dirigido\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(" ng-show=\"v.Dirigido != \'el Imputado,\'\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Especifique:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n            \t <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral("\r\n            \t data-val-required=\"La edad es un campo requerido\"");

WriteLiteral("\r\n                 type=\"text\"");

WriteLiteral(" name=\"Despecify\"");

WriteLiteral(" ng-model=\"v.Despecify\"");

WriteLiteral(" >\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"Despecify\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br />\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" ng-show=\"v.Dirigido == \'la Víctima o testigo\' || v.Dirigido == \'la Fuente,\'\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Relaci&oacute;n:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n             <select");

WriteLiteral(" class=\"form-control element-center\"");

WriteLiteral(" ng-model=\"rel\"");

WriteLiteral(" name=\"Relacion\"");

WriteLiteral("\r\n                        ng-options=\"e.Name for e in lstRel\"");

WriteLiteral("\r\n                        ng-change=\"v.Relationship = rel[\'Name\']\"");

WriteLiteral("\r\n                       ></select>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"Relacion\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br />\r\n\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Direcci&oacute;n:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("\r\n                       data-val=\"true\"");

WriteLiteral("\r\n                       data-val-required=\"La Direcci&oacute;n es un campo reque" +
"rido\"");

WriteLiteral("\r\n                       name=\"Direcci\"");

WriteLiteral(" ng-model=\"v.Direcci\"");

WriteLiteral(" ></textarea>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"Direcci\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br />\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Objetivo de la visita:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("\r\n                       data-val=\"true\"");

WriteLiteral("\r\n                       data-val-required=\"El Objetivo es un campo requerido\"");

WriteLiteral("\r\n                       name=\"Objetivo\"");

WriteLiteral(" ng-model=\"v.Objetivo\"");

WriteLiteral(" ></textarea>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"Objetivo\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br />\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Información proporcionada:\r\n            </div>\r\n            <d" +
"iv");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("\r\n                       data-val=\"true\"");

WriteLiteral("\r\n                       data-val-required=\"La Información proporcionada es un ca" +
"mpo requerido\"");

WriteLiteral("\r\n                       name=\"Info\"");

WriteLiteral(" ng-model=\"v.Info\"");

WriteLiteral(" ></textarea>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"Info\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br />\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Observaciones del supervisor:\r\n            </div>\r\n           " +
" <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("\r\n                       data-val=\"true\"");

WriteLiteral("\r\n                       data-val-required=\"Las Observaciones es un campo requeri" +
"do\"");

WriteLiteral("\r\n                       name=\"Observacion\"");

WriteLiteral(" ng-model=\"v.Observacion\"");

WriteLiteral(" ></textarea>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"Observacion\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br />\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" ng-show=\"v.Dirigido == \'la Víctima o testigo\' || v.Dirigido == \'la Fuente,\'\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Identificaci&oacute;n:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n             <select");

WriteLiteral(" class=\"form-control element-center\"");

WriteLiteral(" ng-model=\"iden\"");

WriteLiteral(" name=\"Identity\"");

WriteLiteral("\r\n                        ng-options=\"e.Name for e in lstDoc\"");

WriteLiteral("\r\n                        ng-change=\"v.Identity = iden[\'Name\']\"");

WriteLiteral("\r\n                       ></select>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"Relacion\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br />\r\n    \t\t\t<div" +
"");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"btn btn-default btn-sm\"");

WriteAttribute ("ng-click", "  ng-click=\"", "\""
, Tuple.Create<string,object,bool> ("", "cancel(", true)

#line 304 "NewLogActivity.cshtml"
                                    , Tuple.Create<string,object,bool> ("", Model.caseDetentionId

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ")", true)
);
WriteLiteral(">\r\n                        Cancelar\r\n                    </span>\r\n               " +
"     <span");

WriteLiteral(" class=\"btn btn-default btn-primary btn-sm\"");

WriteLiteral("\r\n                           ng-click=\"save();\"");

WriteLiteral(@">
                          Guardar
                    </span>
                </div>


</form>
    <script>
        $('.date-picker').datepicker({autoclose:true}).next().on(ace.click_event, function(){
            $(this).prev().focus();
        });
        $('#timepickerStart').timepicker({
            minuteStep: 1,
            showSeconds: false,
            showMeridian: false
        }).next().on(ace.click_event, function(){
                $(this).prev().focus();
            });
    </script>");

}
}
}
#pragma warning restore 1591
