#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmecaApp
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class PersonSocialNetwork : WebViewTemplate
{

#line hidden

#line 1 "PersonSocialNetwork.cshtml"
public UmecaApp.ModelContainer Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 3 "PersonSocialNetwork.cshtml"
  
Layout = "UmecaApp.headUm";


#line default
#line hidden
WriteLiteral("\r\n\r\n<script");

WriteLiteral(" src=\"scripts/app/reviewer/socialNetworkCtrl.js\"");

WriteLiteral("></script>\r\n<div>\r\n    <div");

WriteLiteral(" id=\"dlgUpModalId\"");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" ng-controller=\"socialNetworkController\"");

WriteLiteral(" ng-cloak>\r\n        <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:800px\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"alert alert-info \"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</button>\r\n                        <h4");

WriteLiteral(" class=\"element-center\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-group \"");

WriteLiteral("></i>&nbsp;&nbsp;Persona de su red social</h4>\r\n                    </div>\r\n     " +
"           </div>\r\n                <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                    <form");

WriteLiteral(" id=\"FormSocialNetworkId\"");

WriteLiteral(" name=\"FormSocialNetworkId\"");

WriteLiteral(" ng-submit=\"submit(\'#FormSocialNetworkId\')\"");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(">\r\n                        <br />\r\n                        <!--content begin-->\r\n" +
"<div>\r\n\t<div>\r\n\t    <input");

WriteLiteral(" id=\"hdnJsonAddrssImptd\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute ("value", " value=\"", "\""

#line 24 "PersonSocialNetwork.cshtml"
                  , Tuple.Create<string,object,bool> ("", Model.JsonModel

#line default
#line hidden
, false)
);
WriteLiteral(" name=\"jsonString\"");

WriteLiteral(" />\r\n\t    <input");

WriteLiteral(" id=\"hdnAddrssImptdReference\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute ("value", " value=\"", "\""

#line 25 "PersonSocialNetwork.cshtml"
                       , Tuple.Create<string,object,bool> ("", Model.Reference

#line default
#line hidden
, false)
);
WriteLiteral(" name=\"wasd\"");

WriteLiteral("/>\r\n\t</div>\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" ng-update-hidden");

WriteLiteral(" ng-model=\"id\"");

WriteLiteral(" name=\"idCase\"");

WriteLiteral(" id=\"idCase\"");

WriteLiteral("\r\n           ng-init=\"idCase = ${(idCase == null) ? 0 : idCase};\"");

WriteLiteral(">\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" ng-update-hidden");

WriteLiteral(" ng-model=\"p.relId\"");

WriteLiteral(" name=\"relationship.id\"");

WriteLiteral(" id=\"relId\"");

WriteLiteral("\r\n           ng-init=\"p.relId = ${relId == null ? \"");

WriteLiteral("undefined\" : relId};\">\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" ng-update-hidden");

WriteLiteral(" ng-model=\"p.docId\"");

WriteLiteral(" name=\"documentType.id\"");

WriteLiteral(" id=\"docId\"");

WriteLiteral("\r\n           ng-init=\"p.docId = ${docId == null ? \"");

WriteLiteral("undefined\" : docId};\">\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" ng-update-hidden");

WriteLiteral(" ng-model=\"p.livId\"");

WriteLiteral(" name=\"livingWith.id\"");

WriteLiteral(" id=\"livId\"");

WriteLiteral("\r\n           ng-init=\"p.livId = ${livId == null ? \"");

WriteLiteral("undefined\" : livId};\">\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" ng-update-hidden");

WriteLiteral(" ng-model=\"p.depId\"");

WriteLiteral(" name=\"dependent.id\"");

WriteLiteral(" id=\"depId\"");

WriteLiteral("\r\n           ng-init=\"p.depId = ${depId == null ? \"");

WriteLiteral("undefined\" : depId};\">\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" ng-model=\"person\"");

WriteLiteral(" id=\"person\"");

WriteLiteral("\r\n           ng-init=\'person = ${(p == null) ? \'");

WriteLiteral("{}\': p}\'>\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" ng-update-hidden");

WriteLiteral(" ng-model=\"id\"");

WriteLiteral(" name=\"id\"");

WriteLiteral(" id=\"id\"");

WriteLiteral("\r\n           ng-init=\"id = person.id\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" ng-init=\"p.block =( person.block == undefined)?true:person.block;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-12 element-center\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-6 element-right\"");

WriteLiteral(" >\r\n                &iquest;El imputado cuenta con personas en su red social?\r\n  " +
"          </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-2\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"block\"");

WriteLiteral("\r\n                       id=\"blockYes\"");

WriteLiteral(" ng-value=\"true\"");

WriteLiteral(" ng-model=\"p.block\"");

WriteLiteral(" ng-change=\"fillModel()\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"blockYes\"");

WriteLiteral(">Si</label> &nbsp;&nbsp;&nbsp;\r\n                <input");

WriteLiteral(" type=\"radio\"");

WriteLiteral("  name=\"block\"");

WriteLiteral("\r\n                       id=\"blockNo\"");

WriteLiteral(" ng-value=\"false\"");

WriteLiteral(" ng-model=\"p.block\"");

WriteLiteral(" ng-change=\"fillModel()\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"blockNo\"");

WriteLiteral(">No</label>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"hr hr-3\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-10 col-xs-offset-1\"");

WriteLiteral(" ng-show=\"p.block\"");

WriteLiteral(">\r\n\r\n            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" ng-update-hidden");

WriteLiteral(" name=\"isAccompaniment\"");

WriteLiteral(" ng-model=\"p.isAccompaniment\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" ng-model=\"p.isAccompaniment\"");

WriteLiteral(" id=\"isAccompaniment\"");

WriteLiteral(" ng-checked=\"p.isAccompaniment\"");

WriteLiteral("\r\n                   ng-init=\"p.isAccompaniment =${isAccomp==null ? false: isAcco" +
"mp};\"");

WriteLiteral("  ng-disabled=\"!p.block\"");

WriteLiteral(">\r\n\r\n           <label");

WriteLiteral(" for=\"isAccompaniment\"");

WriteLiteral("> &iquest;Esta persona acompa&ntilde;ar&aacute; al imputado durante el proceso?</" +
"label>\r\n        </div>\r\n    </div>\r\n    <br/>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-2 element-left\"");

WriteLiteral(">\r\n                Nombre:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-10\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"width-100\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("\r\n                       data-val=\"true\"");

WriteLiteral(" data-val-length=\"Debe tener al menos 3 y m&aacute;ximo 150 caracteres\"");

WriteLiteral("\r\n                       data-val-length-max=\"150\"");

WriteLiteral(" data-val-length-min=\"3\"");

WriteLiteral("   ng-readonly=\"!p.block\"");

WriteLiteral("\r\n                       data-val-required=\"El Nombre es un campo requerido\"");

WriteLiteral("\r\n                       name=\"name\"");

WriteLiteral(" id=\"name\"");

WriteLiteral(" ng-init=\"name = person.name\"");

WriteLiteral(" value=\"{{name}}\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"name\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n        </div>\r\n    </div>\r\n    </div>\r\n    <br/>\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Relaci&oacute;n:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <select");

WriteLiteral(" class=\"form-control element-center\"");

WriteLiteral(" ng-model=\"p.rel\"");

WriteLiteral("\r\n                        ng-options=\"e.name for e in lstRel\"");

WriteLiteral("\r\n                        ng-change=\"p.relId = p.rel.id\"");

WriteLiteral("   ng-readonly=\"!p.block\"");

WriteLiteral("\r\n                        ng-init=\'lstRel = ${lstRelationship};\'");

WriteLiteral("></select>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-9 col-xs-offset-3\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"lastName1\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Tel&eacute;fono:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" type=\"text\"");

WriteLiteral("  ng-readonly=\"!p.block\"");

WriteLiteral("\r\n                       data-val=\"true\"");

WriteLiteral(" data-val-length=\"Debe tener al menos 5 y m&aacute;ximo 200 caracteres\"");

WriteLiteral("\r\n                       data-val-length-max=\"200\"");

WriteLiteral(" data-val-length-min=\"5\"");

WriteLiteral("\r\n                       data-val-required=\"El tel&eacute;fono es un campo requer" +
"ido\"");

WriteLiteral("\r\n                       name=\"phone\"");

WriteLiteral(" id=\"phone\"");

WriteLiteral(" ng-model=\"phone\"");

WriteLiteral(" ng-init=\"phone = person.phone\"");

WriteLiteral("></textarea>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"phone\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br/>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" ng-show=\"p.rel.specification == true\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Especif&iacute;que<br/>relaci&oacute;n:\r\n            </div>\r\n " +
"           <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral("\r\n                       data-val-length=\"Debe tener al menos 2 y m&aacute;ximo 2" +
"55 caracteres\"");

WriteLiteral("\r\n                       data-val-length-max=\"255\"");

WriteLiteral(" data-val-length-min=\"2\"");

WriteLiteral("\r\n                       data-val-required=\"La especificaci&oacute;n es un campo " +
"requerido\"");

WriteLiteral("\r\n                       type=\"text\"");

WriteLiteral(" ng-model=\"specificationRelationship\"");

WriteLiteral(" ng-init=\"specificationRelationship = person.specificationRelationship\"");

WriteLiteral("\r\n                       id=\"specificationRelationship\"");

WriteLiteral(" name=\"specificationRelationship\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-9 col-xs-offset-3\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"specificationRelationship\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n\r\n    </div>\r\n    <br/>\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Identificaci&oacute;n prensentada:\r\n            </div>\r\n      " +
"      <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <select");

WriteLiteral(" class=\"form-control element-center\"");

WriteLiteral(" ng-model=\"p.doc\"");

WriteLiteral("\r\n                        ng-options=\"e.name for e in lstDoc\"");

WriteLiteral("\r\n                        ng-change=\"p.docId = p.doc.id\"");

WriteLiteral("  ng-readonly=\"!p.block\"");

WriteLiteral("\r\n                        ng-init=\'lstDoc = ${lstDocumentType};\'");

WriteLiteral("></select>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Edad:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral("\r\n                       data-val-length=\"Debe tener al menos 1 y m&aacute;ximo 2" +
" n&uacute;mero\"");

WriteLiteral("\r\n                       data-val-regex-pattern=\"([0-9]+)\"");

WriteLiteral("    ng-readonly=\"!p.block\"");

WriteLiteral("\r\n                       data-val-regex=\"La edad s&oacute;lo puede contener n&uac" +
"ute;meros\"");

WriteLiteral("\r\n                       data-val-length-max=\"2\"");

WriteLiteral(" data-val-length-min=\"1\"");

WriteLiteral(" data-val-required=\"La edad es un campo requerido\"");

WriteLiteral("\r\n                       type=\"text\"");

WriteLiteral(" name=\"age\"");

WriteLiteral(" ng-init=\"age = person.age\"");

WriteLiteral(" value=\"{{age}}\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"age\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br/>\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" ng-show=\"p.doc.specification == true\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Especif&iacute;que:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral("\r\n                       data-val-length=\"Debe tener al menos 2 y m&aacute;ximo 2" +
"55 caracteres\"");

WriteLiteral("\r\n                       data-val-length-max=\"255\"");

WriteLiteral(" data-val-length-min=\"2\"");

WriteLiteral("\r\n                       data-val-required=\"La especificaci&oacute;n es un campo " +
"requerido\"");

WriteLiteral("\r\n                       type=\"text\"");

WriteLiteral(" ng-model=\"specification\"");

WriteLiteral(" ng-init=\"specification = person.specification\"");

WriteLiteral("\r\n                       id=\"specification\"");

WriteLiteral(" name=\"specification\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-9 col-xs-offset-3\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"specification\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br/>\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Vive con el:\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <select");

WriteLiteral(" class=\"form-control element-center\"");

WriteLiteral(" ng-model=\"p.liv\"");

WriteLiteral("\r\n                        ng-options=\"e.name for e in lstLiv\"");

WriteLiteral("\r\n                        ng-change=\"p.livId = p.liv.id\"");

WriteLiteral("  ng-readonly=\"!p.block\"");

WriteLiteral("\r\n                        ng-init=\'lstLiv = ${lstElection};\'");

WriteLiteral("></select>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-9 col-xs-offset-3\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"lastName1\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-4 element-left\"");

WriteLiteral(">\r\n                Dependiente econ&oacute;mico:\r\n            </div>\r\n           " +
" <div");

WriteLiteral(" class=\"col-xs-8\"");

WriteLiteral(">\r\n                <select");

WriteLiteral(" class=\"form-control element-center\"");

WriteLiteral(" ng-model=\"p.dep\"");

WriteLiteral("\r\n                        ng-options=\"e.name for e in lstDep\"");

WriteLiteral("\r\n                        ng-change=\"p.depId = p.dep.id\"");

WriteLiteral("   ng-readonly=\"!p.block\"");

WriteLiteral("\r\n                        ng-init=\'lstDep = ${lstElection};\'");

WriteLiteral("></select>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-xs-9 col-xs-offset-3\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"lastName1\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br/>\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" ng-show=\"p.livId == 2\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-xs-2 element-left\"");

WriteLiteral(">Direcci&oacute;n:</div>\r\n            <div");

WriteLiteral(" class=\"col-xs-10\"");

WriteLiteral(">\r\n                <textarea");

WriteLiteral(" id=\"address\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"address\"");

WriteLiteral(" ng-model=\"address\"");

WriteLiteral("\r\n                          ng-init=\"address = person.address\"");

WriteLiteral("\r\n                          data-val=\"true\"");

WriteLiteral(" data-val-required=\"La direcci&oacute;n es un campo requerido\"");

WriteLiteral("\r\n                          data-val-length=\"Debe tener al menos 6 y m&aacute;xim" +
"o 500 caracteres\"");

WriteLiteral("\r\n                          data-val-length-max=\"500\"");

WriteLiteral(" data-val-length-min=\"6\"");

WriteLiteral("></textarea>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-xs-10 col-xs-offset-2\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"address\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n        </div>\r\n    </div>\r\n\r\n</div>\r\n</form>\r\n                    <br " +
"/>\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" ng-show=\"MsgError\"");

WriteLiteral(" class=\"alert alert-danger element-center\"");

WriteLiteral(">\r\n                                {{MsgError}}\r\n                            </di" +
"v>\r\n                        </div>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"btn btn-default btn-sm\"");

WriteLiteral(" ng-click=\"cancel()\"");

WriteLiteral(">\r\n                        Cancelar\r\n                    </span>\r\n               " +
"     <span");

WriteLiteral(" class=\"btn btn-default btn-primary btn-sm\"");

WriteLiteral(" ng-disabled=\"WaitFor==true\"");

WriteLiteral("\r\n                          ng-click=\"submit(\'#FormSocialNetworkId\', \'<c:url valu" +
"e=\"");

WriteLiteral("/");

WriteLiteral("reviewer/meeting/socialNetwork/doUpsert.json?idCase=${idCase}");

WriteLiteral("\"/>\');\">\r\n                          Guardar\r\n                    </span>\r\n       " +
"         </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

}
}
}
#pragma warning restore 1591
