#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmecaApp
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class SyncCaseList : WebViewTemplate
{

#line hidden

#line 1 "SyncCaseList.cshtml"
public System.Collections.Generic.List<UmecaApp.MeetingTblDto> Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 3 "SyncCaseList.cshtml"
  
	Layout = "UmecaApp.headUmGrid";


#line default
#line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    function legal(err){
    	alert(""legal>>""+err);
    }
    function syncronizar(idMeet){
    var casos = ""[""+idMeet+""]"";
    	var result = Sync.sincrinozeCase(casos, ""99630110"");
    }
    function cancelari(){
		window.location.replace('hybrid:Login/Index');
    }
    </script>
<h2");

WriteLiteral(" class=\"element-center\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-comments-alt \"");

WriteLiteral("></i>&nbsp;&nbsp;Entrevistas de evaluaci&oacute;n de riesgos procesales</h2>\r\n<br" +
" />\r\n<div");

WriteLiteral(" id=\"toolbar2\"");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n    <a");

WriteAttribute ("href", " href=\"", "\""

#line 21 "SyncCaseList.cshtml"
, Tuple.Create<string,object,bool> ("", Url.Action("MeetingEditNew","Meeting")

#line default
#line hidden
, false)
);
WriteLiteral(">\r\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" id=\"btnAdd\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></i>\r\n    </button></a>\r\n    <!--<button type=\"button\" class=\"btn btn-default\" i" +
"d=\"btnRefresh\">\r\n        <i class=\"glyphicon glyphicon-refresh\"></i>\r\n    </butt" +
"on>-->\r\n</div>\r\n    <table");

WriteLiteral(" data-toggle=\"table\"");

WriteLiteral(" data-page-size=\"10\"");

WriteLiteral(" data-page-list=\"[10, 20, 30]\"");

WriteLiteral("\r\n     data-pagination=\"true\"");

WriteLiteral(" data-height=\"250\"");

WriteLiteral("\r\n     data-striped=\"true\"");

WriteLiteral(" data-search=\"true\"");

WriteLiteral(" \r\n     data-search-align=\"right\"");

WriteLiteral(" data-toolbar=\"#toolbar2\"");

WriteLiteral(">\r\n    <thead>\r\n    <tr>\r\n        <th>ID</th>\r\n        <th");

WriteLiteral(" data-width=\"900\"");

WriteLiteral(">Carpeta de Investigaci&oacute;n</th>\r\n        <th>Nombre completo</th>\r\n        " +
"<th>Estatus</th>\r\n        <th>sincronization Type</th>\r\n        <th>Acci&oacute;" +
"n</th>\r\n    </tr>\r\n    </thead>\r\n    <tbody> \r\n");


#line 44 "SyncCaseList.cshtml"
    

#line default
#line hidden

#line 44 "SyncCaseList.cshtml"
     foreach(var Meeting in Model) {


#line default
#line hidden
WriteLiteral("    <tr");

WriteLiteral(" id=\"tr-id-1\"");

WriteLiteral(" class=\"tr-class-1\"");

WriteLiteral(">\r\n        <td");

WriteLiteral(" id=\"td-id-1\"");

WriteLiteral(" class=\"td-class-1\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");


#line 47 "SyncCaseList.cshtml"
       Write(Meeting.CaseId);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 50 "SyncCaseList.cshtml"
       Write(Meeting.IdFolder);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 53 "SyncCaseList.cshtml"
        Write(Meeting.Name+" "+Meeting.LastNameP+" "+Meeting.LastNameM);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("       \t\t");


#line 56 "SyncCaseList.cshtml"
       Write(Meeting.StatusCode);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("        \t");


#line 59 "SyncCaseList.cshtml"
       Write(Meeting.Action);


#line default
#line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n         \t<a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" style=\"display:inline-block;\"");

WriteLiteral(" title=\"Sincronizar\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "syncronizar(", true)

#line 62 "SyncCaseList.cshtml"
                                                                   , Tuple.Create<string,object,bool> ("", Meeting.CaseId

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ");", true)
);
WriteLiteral("><i");

WriteLiteral(" class=\"icon-exchange\"");

WriteLiteral("></i></a>\r\n        </td>\r\n    </tr>\r\n");


#line 65 "SyncCaseList.cshtml"
}


#line default
#line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n\t<!--<span class=\"btn btn-default btn-sm\" onclick=\"cancel" +
"ari();\">\r\n        Cancelar\r\n    </span>-->");

}
}
}
#pragma warning restore 1591
