#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmecaApp
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class VerificationSourceList : WebViewTemplate
{

#line hidden

#line 1 "VerificationSourceList.cshtml"
public UmecaApp.SourcesTblDto Model { get; set; }

#line default
#line hidden


public override void Execute()
{

#line 3 "VerificationSourceList.cshtml"
  
	Layout = "UmecaApp.headUm";


#line default
#line hidden
WriteLiteral("\r\n\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    app.controller('SourcesListControler', function($scope, $http, $timeout, $sce){

    $scope.m = {};
    $scope.listSources=[];

    $timeout(function () {
    		$scope.init();

	}, 0);

	$scope.init = function(){
	    try{
	    console.log(""wasd"");
	    }
	    catch(err){
	    	alert(""error catched Iniciate angular function erro==>""+err.message);
	    }
	};
   
});

	window.SourceMeeting = function(id){
    	var iner = parseInt(id);
    	window.location.replace('hybrid:Verification/ValidationMeetingBySource?idSource='+iner);
	}

</script>

<div");

WriteLiteral(" ng-app=\"umecaMobile\"");

WriteLiteral(" ng-controller=\"SourcesListControler\"");

WriteLiteral(">\r\n\r\n\r\n<h2");

WriteLiteral(" class=\"element-center\"");

WriteLiteral("><i");

WriteLiteral(" class=\" icon-group\"");

WriteLiteral("></i>&nbsp;&nbsp;Fuentes de verificaci&oacute;n</h2>\r\n\r\n\r\n\t<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"header smaller lighter blue\"");

WriteLiteral(" >\r\n                <small>Carpeta de investigaci&oacute;n:  </small>\r\n          " +
"     &nbsp;");


#line 47 "VerificationSourceList.cshtml"
                Write(Model.IdFolder);


#line default
#line hidden
WriteLiteral("\r\n            </h3>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"header smaller lighter blue\"");

WriteLiteral(">\r\n                <small>Nombre del imputado:  </small>\r\n                &nbsp;");


#line 53 "VerificationSourceList.cshtml"
                 Write(Model.FullnameImputed);


#line default
#line hidden
WriteLiteral("\r\n            </h3>\r\n        </div>\r\n         <div");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">\r\n                <h3");

WriteLiteral(" class=\"header smaller lighter blue\"");

WriteLiteral(">\r\n                    <small>Edad:  </small>\r\n                    &nbsp;");


#line 59 "VerificationSourceList.cshtml"
                     Write(Model.Age);


#line default
#line hidden
WriteLiteral("\r\n                </h3>\r\n            </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteAttribute ("ng-show", " ng-show=\"", "\""
, Tuple.Create<string,object,bool> ("", "\'", true)

#line 64 "VerificationSourceList.cshtml"
, Tuple.Create<string,object,bool> ("", Model.tStart

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\'==\'\'?false:true", true)
);
WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"header smaller lighter blue\"");

WriteLiteral(">\r\n                <small>Entrevista de riesgos procesales:  </small>\r\n          " +
"      &nbsp;");


#line 68 "VerificationSourceList.cshtml"
                 Write(Model.tEnd);


#line default
#line hidden
WriteLiteral("\r\n            </h3>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"header smaller lighter blue\"");

WriteLiteral(">\r\n                <small>Evaluador:  </small>\r\n                &nbsp;");


#line 74 "VerificationSourceList.cshtml"
                 Write(Model.reviewerFullname);


#line default
#line hidden
WriteLiteral("\r\n            </h3>\r\n        </div>\r\n    </div>\r\n    <table");

WriteLiteral(" data-toggle=\"table\"");

WriteLiteral(" data-page-size=\"10\"");

WriteLiteral(" data-page-list=\"[10, 20, 30]\"");

WriteLiteral("\r\n     data-pagination=\"true\"");

WriteLiteral(" data-height=\"250\"");

WriteLiteral("\r\n     data-striped=\"true\"");

WriteLiteral(" data-search=\"true\"");

WriteLiteral(" \r\n     data-search-align=\"right\"");

WriteLiteral(" data-toolbar=\"#toolbar2\"");

WriteAttribute ("ng-init", " ng-init=\'", "\'"
, Tuple.Create<string,object,bool> ("", "listSources", true)
, Tuple.Create<string,object,bool> (" ", "=", true)

#line 81 "VerificationSourceList.cshtml"
                                       , Tuple.Create<string,object,bool> (" ", Model.SourceListJson

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", ";", true)
);
WriteLiteral(" >\r\n    <thead>\r\n    <tr>\r\n        <th");

WriteLiteral(" ng-click=\"init();\"");

WriteLiteral(">Nombre</th>\r\n        <th>Edad</th>\r\n        <th>Relaci&oacute;n</th>\r\n        <t" +
"h>Direcci&oacute;n</th>\r\n        <th>Tel&eacute;fono</th>\r\n        <th>Estatus</" +
"th>\r\n        <th>Acci&oacute;n</th>\r\n    </tr>\r\n    </thead>\r\n\r\n    <tbody>\r\n   " +
" <tr");

WriteLiteral(" class=\"tr-class-1\"");

WriteLiteral(" ng-repeat =\"src in listSources track by $index\" >\r\n    \t<td");

WriteLiteral(" class=\"td-class-1\"");

WriteLiteral(">\r\n           {{src.FullName}}\r\n        </td>\r\n        <td>\r\n        \t{{src.Age}}" +
"\r\n        </td>\r\n        <td");

WriteLiteral(" on=\"src.RelationshipId\"");

WriteLiteral(" ng-switch >\r\n\t\t\t<label");

WriteLiteral(" ng-switch-when=\"18\"");

WriteLiteral(" >\r\n\t\t\tAbuelo</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"6\"");

WriteLiteral(" >\r\n             Amigo</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"10\"");

WriteLiteral(" >\r\n             Compañero de trabajo</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"12\"");

WriteLiteral(" >\r\n             Empleado</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"14\"");

WriteLiteral(" >\r\n             Esposa</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"16\"");

WriteLiteral(" >\r\n             Familiar Político</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"1\"");

WriteLiteral(" >\r\n             Hermano</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"3\"");

WriteLiteral(" >\r\n             Hijo(a)</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"20\"");

WriteLiteral(" >\r\n             Imputado</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"2\"");

WriteLiteral(" >\r\n             Madre</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"8\"");

WriteLiteral(" >\r\n             Ninguno</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"19\"");

WriteLiteral(" >\r\n             Otro</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"17\"");

WriteLiteral(" >\r\n             Padre</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"11\"");

WriteLiteral(" >\r\n             Padrino</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"13\"");

WriteLiteral(" >\r\n             Pareja sentimental</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"9\"");

WriteLiteral(" >\r\n             Patrón</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"4\"");

WriteLiteral(" >\r\n             Primo(a)</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"15\"");

WriteLiteral(" >\r\n             Suegra</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"5\"");

WriteLiteral(" >\r\n             Tío(a)</label>\r\n            <label");

WriteLiteral(" ng-switch-when=\"7\"");

WriteLiteral(@" >
             Vecino</label>
            <label ng-switch-default >
             </label>
        </td>
        <td >
            {{src.Address}}
        </td>
        <td>
        	{{src.Phone}}
        </td>
        <td>
        	{{src.StatusString}}
        </td>
        <td");

WriteLiteral(" id=\"valor\"");

WriteLiteral(">\r\n\t\t\t<a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral("  onclick=\'SourceMeeting($(this).text());\'");

WriteLiteral(" ng-click=\'src.Id = 4\'");

WriteLiteral(" style=\"display:inline-block;\"");

WriteLiteral(" title=\"Entrevistar fuentes\"");

WriteLiteral(" >\r\n\t\t\t\t<label");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">{{src.Id}}</label>\r\n\t\t\t\t<i");

WriteLiteral(" class=\"icon-edit blue\"");

WriteLiteral("></i>\r\n\t\t\t</a>\r\n        </td>\r\n\t</tr>\r\n    </tbody>\r\n</table>\r\n<script>\r\n functio" +
"n cancelari(){\r\n\t\twindow.location.replace(\'hybrid:Verification/Index\');\r\n    }\r\n" +
"</script>\r\n\t<span");

WriteLiteral(" class=\"btn btn-default btn-sm\"");

WriteLiteral(" onclick=\"cancelari();\"");

WriteLiteral(">\r\n        Cancelar\r\n    </span>\r\n</div>");

}
}
}
#pragma warning restore 1591
