//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmecaApp.localhostUmecaWs {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UmecaWSSoap11Binding", Namespace="http://ws.umeca.com")]
    public partial class UmecaWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public UmecaWS() {
			this.Url = "http://192.168.1.9:8080/anelumeca/services/UmecaWS.UmecaWSHttpSoap11Endpoint/";
        }
        
        public UmecaWS(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getAssignmentsByUser", RequestNamespace="http://ws.umeca.com", ResponseNamespace="http://ws.umeca.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getAssignmentsByUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string user, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid) {
            object[] results = this.Invoke("getAssignmentsByUser", new object[] {
                        user,
                        guid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAssignmentsByUser(string user, string guid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAssignmentsByUser", new object[] {
                        user,
                        guid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAssignmentsByUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:loginFromTablet", RequestNamespace="http://ws.umeca.com", ResponseNamespace="http://ws.umeca.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string loginFromTablet([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string user, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string encodedPass) {
            object[] results = this.Invoke("loginFromTablet", new object[] {
                        user,
                        encodedPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginloginFromTablet(string user, string encodedPass, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("loginFromTablet", new object[] {
                        user,
                        encodedPass}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndloginFromTablet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getAssignedCaseByAssignmentId", RequestNamespace="http://ws.umeca.com", ResponseNamespace="http://ws.umeca.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getAssignedCaseByAssignmentId([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string user, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string guid, long assignmentId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool assignmentIdSpecified) {
            object[] results = this.Invoke("getAssignedCaseByAssignmentId", new object[] {
                        user,
                        guid,
                        assignmentId,
                        assignmentIdSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAssignedCaseByAssignmentId(string user, string guid, long assignmentId, bool assignmentIdSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAssignedCaseByAssignmentId", new object[] {
                        user,
                        guid,
                        assignmentId,
                        assignmentIdSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetAssignedCaseByAssignmentId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
