#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmecaApp
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class headUmGrid : WebViewTemplate
{

#line hidden

public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n\t<head>\r\n\t\t<title>Umeca</title>\r\n\t\t//CSS content/themes/" +
"umeca\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"content/themes/umeca/ace-fonts.css\"");

WriteLiteral("/>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"content/themes/umeca/ace-rtl.min.css\"");

WriteLiteral("/>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"content/themes/umeca/ace-skins.min.css\"");

WriteLiteral("/>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"content/themes/umeca/ace.min.css\"");

WriteLiteral("/>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"content/themes/umeca/bootstrap-timepicker.css\"");

WriteLiteral("/>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"content/themes/umeca/datepicker.css\"");

WriteLiteral("/>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"content/themes/umeca/font-awesome.min.css\"");

WriteLiteral("/>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"content/themes/umeca/jquery-ui-1.10.3.full.min.css\"");

WriteLiteral("/>\r\n       \r\n    //CSS Content Root directory\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"content/bootstrap.css\"");

WriteLiteral("/>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"content/Site.css\"");

WriteLiteral("/>\r\n\r\n    //Scripts from scripts root directory\r\n    <script");

WriteLiteral(" src=\"scripts/jquery-1.10.2.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"scripts/umeca/bootstrap.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"scripts/common.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"scripts/modernizr-2.6.2.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"scripts/respond.min.js\"");

WriteLiteral("></script>\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"bootstrap-table/bootstrap-table.css\"");

WriteLiteral(">\r\n    <script");

WriteLiteral(" src=\"bootstrap-table/bootstrap-table.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"bootstrap-table/bootstrap-table-es-AR.min.js\"");

WriteLiteral("></script>\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">
        .pagination-info {
        float: right;!important;
        }
        div.pagination {
            width: 55%!important;
        float: left!important;
        }
        ul.pagination {
            display: inline-block!important;
            text-align: right!important;
            float: right!important;
        }
        .page-list {
        float: left!important;
        padding-left: 5px;
        }
        .pagination-detail{
            width: 45%!important;
            float: right!important;
            padding-top: 10px;
        }
    </style>

    //umeca root scripts
    <script");

WriteLiteral(" src=\"scripts/umeca/ace-elements.min.js\"");

WriteLiteral("></script>\r\n    \t<script");

WriteLiteral(" src=\"scripts/umeca/ace-extra.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"scripts/umeca/ace.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"scripts/umeca/typeahead-bs2.min.js\"");

WriteLiteral("></script>\r\n    \t//layout\r\n\t</head>\r\n\t<body>\r\n");

WriteLiteral("\t\t");


#line 62 "headUmGrid.cshtml"
Write(RenderBody());


#line default
#line hidden
WriteLiteral("\r\n\t</body>\r\n</html>");

}
}
}
#pragma warning restore 1591
