#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmecaApp
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class MainLayout : WebViewTemplate
{

#line hidden

public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n\t<head>\r\n\t\t<title>");


#line 5 "MainLayout.cshtml"
    Write(ViewBag.Title);


#line default
#line hidden
WriteLiteral("</title>\r\n\t</head>\r\n\t<body");

WriteLiteral(" style=\"background-color: green;\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t");


#line 8 "MainLayout.cshtml"
Write(RenderBody());


#line default
#line hidden
WriteLiteral("\r\n\t</body>\r\n</html>");

}
}
}
#pragma warning restore 1591
